import { createHash, randomUUID } from "node:crypto";
import type { RequestContext } from "../agreements/application/contracts.ts";
import { DeterministicAssessmentAdapter } from "../evidence/adapter.ts";
import { requirementState, type ReviewReason } from "../evidence/domain.ts";
import type { EvidenceAssessmentService, WorkflowRepository } from "../evidence/service.ts";
import { EvidenceError, resolvePolicy, validateMetadata } from "../evidence/validation.ts";
import { retrieveFixture } from "./fixtures.ts";
import { issueReceipt, verifyReceipt, type RetrievalReceipt } from "./security.ts";

const hash = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
const assertObject = (value: unknown) => { if (!value || typeof value !== "object" || Array.isArray(value)) throw new EvidenceError("INVALID_REQUEST", "The tool input is invalid.", 400); return value as Record<string, unknown>; };
const strict = (value: unknown, allowed: readonly string[]) => { const input = assertObject(value); if (Object.keys(input).some((key) => !allowed.includes(key))) throw new EvidenceError("INVALID_REQUEST", "The tool input contains an unsupported field.", 400); return input; };
const text = (input: Record<string, unknown>, key: string, max = 128) => { const value = input[key]; if (typeof value !== "string" || value.length < 1 || value.length > max || /[\u0000-\u001f]/.test(value)) throw new EvidenceError("INVALID_REQUEST", "The tool input is invalid.", 400); return value; };
const strings = (input: Record<string, unknown>, key: string, max = 100) => { const value = input[key]; if (!Array.isArray(value) || value.length < 1 || value.length > max || value.some((item) => typeof item !== "string" || item.length > 128)) throw new EvidenceError("INVALID_REQUEST", "The tool input is invalid.", 400); return [...new Set(value as string[])]; };
const contract = (input: Record<string, unknown>) => { if (input.contractVersion !== "2026-08-06") throw new EvidenceError("CONTRACT_VERSION_UNSUPPORTED", "The MCP contract version is not supported.", 400); };
const minimizeRequirement = <T extends { submitterPartyIds: string[] }>(requirement: T) => Object.fromEntries(Object.entries(requirement).filter(([key]) => key !== "submitterPartyIds"));

export interface ProvenanceEvent { requestId: string; tool: string; actorId: string; occurredAt: string; contractVersion: string; policyVersion?: string; providerKind?: "deterministic_local" | "future_model"; providerVersion?: string; adapterVersion?: string; promptVersion?: string; modelVersion?: string; toolVersion: "mcp-tools-v1"; inputDigest: string; outputDigest?: string; evidenceSetId?: string; outcome: "succeeded" | "failed" }
export class VerificationFacade {
  readonly provenance: ProvenanceEvent[] = [];
  private readonly receiptUses = new Map<string, { fingerprint: string; expiresAt: number }>();
  private readonly repository: WorkflowRepository; private readonly service: EvidenceAssessmentService; private readonly secret: string; private readonly now: () => Date;
  constructor(repository: WorkflowRepository, service: EvidenceAssessmentService, secret: string, now: () => Date = () => new Date()) { this.repository = repository; this.service = service; this.secret = secret; this.now = now; }
  private account(context: RequestContext) { if (context.principal.kind !== "account") throw new EvidenceError("AUTHENTICATION_REQUIRED", "Local MCP authentication is required.", 401); return context.principal.accountId; }
  private async agreement(context: RequestContext, agreementId: string, versionId: string) { await this.service.workflowContext(context, agreementId, versionId); const value = await this.repository.agreement(agreementId, versionId); if (!value) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); return value; }
  private record(context: RequestContext, tool: string, input: unknown, result: unknown, extra: Partial<ProvenanceEvent> = {}) { this.provenance.push({ requestId: context.requestId, tool, actorId: this.account(context), occurredAt: this.now().toISOString(), contractVersion: "2026-08-06", toolVersion: "mcp-tools-v1", inputDigest: hash(input), outputDigest: hash(result), outcome: "succeeded", ...extra }); if (this.provenance.length > 1_000) this.provenance.shift(); }
  async getTerms(context: RequestContext, raw: unknown) { const input = strict(raw, ["contractVersion", "agreementId", "versionId"]); contract(input); const agreementId = text(input, "agreementId"), versionId = text(input, "versionId"); const { document } = await this.agreement(context, agreementId, versionId); const visible = await this.service.authorizedRequirements(context, agreementId, versionId); const sourceIds = new Set(visible.flatMap((item) => item.sourceConstraintIds)); const result = { agreementId, versionId, acceptedVersionProven: true, purpose: document.purpose, criteria: document.terms.successCriteria.filter((item) => item.evidenceRequirementIds.some((id) => visible.some((requirement) => requirement.evidenceRequirementId === id))), evidenceRequirements: visible.map(minimizeRequirement), sourceConstraints: document.evidencePolicy.sourceConstraints.filter((item) => sourceIds.has(item.sourceConstraintId)), verificationPolicy: document.verificationPolicy, resolutionContext: { humanDecisionRequired: true, settlementAuthority: false } }; this.record(context, "hmm_get_agreement_terms", input, result, { policyVersion: document.verificationPolicy.policyVersion }); return result; }
  async getRequirements(context: RequestContext, raw: unknown) { const input = strict(raw, ["contractVersion", "agreementId", "versionId", "criterionIds"]); contract(input); const agreementId = text(input, "agreementId"), versionId = text(input, "versionId"); const { document } = await this.agreement(context, agreementId, versionId); const wanted = input.criterionIds === undefined ? null : new Set(strings(input, "criterionIds")); const evidence = await this.service.listEvidence(context, agreementId, versionId); const visible = await this.service.authorizedRequirements(context, agreementId, versionId); const result = visible.filter((r) => !wanted || r.criterionIds.some((id) => wanted.has(id))).map((requirement) => ({ ...minimizeRequirement(requirement), state: requirementState(evidence.filter((item) => item.evidenceRequirementId === requirement.evidenceRequirementId).map((item) => item.currentRevision), requirement.minimumDistinctSources, requirement.independentSourcesRequired) })); this.record(context, "hmm_get_evidence_requirements", input, result, { policyVersion: document.verificationPolicy.policyVersion }); return result; }
  async listEvidence(context: RequestContext, raw: unknown) { const input = strict(raw, ["contractVersion", "agreementId", "versionId", "criterionId", "cursor", "pageSize"]); contract(input); const agreementId = text(input, "agreementId"), versionId = text(input, "versionId"); await this.agreement(context, agreementId, versionId); const all = (await this.service.listEvidence(context, agreementId, versionId)).filter((item) => !input.criterionId || item.currentRevision.criterionIds.includes(text(input, "criterionId"))); const size = input.pageSize === undefined ? 25 : input.pageSize; if (!Number.isInteger(size) || (size as number) < 1 || (size as number) > 50) throw new EvidenceError("INVALID_REQUEST", "The page size is invalid.", 400); const offset = input.cursor === undefined ? 0 : Number.parseInt(Buffer.from(text(input, "cursor", 64), "base64url").toString("utf8"), 10); if (!Number.isSafeInteger(offset) || offset < 0) throw new EvidenceError("INVALID_REQUEST", "The cursor is invalid.", 400); const data = all.slice(offset, offset + (size as number)).map((item) => ({ evidenceId: item.evidenceId, evidenceRevisionId: item.currentRevisionId, evidenceRequirementId: item.evidenceRequirementId, evidenceClass: item.currentRevision.evidenceClass, origin: item.currentRevision.origin, sourceConstraintId: item.currentRevision.sourceConstraintId, sourceDisplayLabel: item.currentRevision.sourceDisplayLabel, capturedAt: item.currentRevision.capturedAt, observedAt: item.currentRevision.observedAt, receivedAt: item.currentRevision.receivedAt, availability: item.currentRevision.availability, integrity: item.currentRevision.integrity, validation: item.currentRevision.validation, criterionIds: item.currentRevision.criterionIds, provenance: { contentDigest: item.currentRevision.contentDigest, sourceRefKind: item.currentRevision.sourceRefKind } })); const next = offset + data.length < all.length ? Buffer.from(String(offset + data.length)).toString("base64url") : null; const result = { data, page: { nextCursor: next, hasMore: next !== null } }; this.record(context, "hmm_list_evidence_metadata", input, result); return result; }
  async getAssessment(context: RequestContext, raw: unknown) { const input = strict(raw, ["contractVersion", "agreementId", "assessmentId"]); contract(input); const result = await this.service.getAssessment(context, text(input, "agreementId"), text(input, "assessmentId")); this.record(context, "hmm_get_assessment", input, result, { policyVersion: result.policyVersion, adapterVersion: result.adapterVersion, evidenceSetId: result.evidenceSetId }); return { ...result, authority: "advisory_only", chainOfThought: undefined }; }
  async retrieve(context: RequestContext, raw: unknown) { const input = strict(raw, ["contractVersion", "agreementId", "versionId", "sourceConstraintId", "fixtureId", "fields"]); contract(input); const agreementId = text(input, "agreementId"), versionId = text(input, "versionId"), sourceConstraintId = text(input, "sourceConstraintId"), fixtureId = text(input, "fixtureId"); const fields = strings(input, "fields", 20); const { document } = await this.agreement(context, agreementId, versionId); const source = document.evidencePolicy.sourceConstraints.find((item) => item.sourceConstraintId === sourceConstraintId); if (!source || fields.some((field) => !source.permittedFields.includes(field))) throw new EvidenceError("SOURCE_NOT_ALLOWED", "The approved source reference is not allowed.", 404); const fixture = retrieveFixture(fixtureId, sourceConstraintId, fields); const now = Math.floor(this.now().getTime() / 1000); const receipt: RetrievalReceipt = { receiptId: `receipt-${randomUUID()}`, accountId: this.account(context), agreementId, versionId, sourceConstraintId, adapterVersion: fixture.schemaVersion, fixtureId, referenceDigest: hash(fixtureId), fields, capturedAt: fixture.capturedAt, digest: fixture.digest, correlationId: context.correlationId, issuedAt: now, expiresAt: now + 300 }; const result = { observation: fixture.fields, capturedAt: fixture.capturedAt, publisher: fixture.publisher, synthetic: true, untrustedContent: true, contentDigest: fixture.digest, retrievalReceiptId: issueReceipt(receipt, this.secret) }; this.record(context, "hmm_retrieve_approved_source", input, result, { policyVersion: document.verificationPolicy.policyVersion }); return result; }
  async submitObservation(context: RequestContext, raw: unknown) { const input = strict(raw, ["contractVersion", "agreementId", "versionId", "evidenceRequirementId", "criterionIds", "sourceConstraintId", "retrievalReceiptId", "metadata", "capturedAt", "observedAt", "idempotencyKey"]); contract(input); const agreementId = text(input, "agreementId"), versionId = text(input, "versionId"), requirementId = text(input, "evidenceRequirementId"), sourceConstraintId = text(input, "sourceConstraintId"); const criteria = strings(input, "criterionIds"); const now = Math.floor(this.now().getTime() / 1000); const receipt = verifyReceipt(text(input, "retrievalReceiptId", 4096), this.secret, now); if (receipt.accountId !== this.account(context) || receipt.agreementId !== agreementId || receipt.versionId !== versionId || receipt.sourceConstraintId !== sourceConstraintId || receipt.capturedAt !== text(input, "capturedAt")) throw new EvidenceError("RECEIPT_SCOPE_MISMATCH", "The retrieval receipt does not match this request.", 404); const { document } = await this.agreement(context, agreementId, versionId); const { source } = resolvePolicy(requirementId, sourceConstraintId, document); const metadata = validateMetadata(input.metadata, source); if (hash({ fixtureId: receipt.fixtureId, schemaVersion: "fixture-v1", fields: metadata }) !== receipt.digest) throw new EvidenceError("RECEIPT_SCOPE_MISMATCH", "The observation does not match the retrieval receipt.", 400); const fingerprint = hash(input); for (const [id, use] of this.receiptUses) if (use.expiresAt <= now) this.receiptUses.delete(id); const prior = this.receiptUses.get(receipt.receiptId); if (prior && prior.fingerprint !== fingerprint) throw new EvidenceError("RECEIPT_REPLAYED", "The retrieval receipt was already used for a different request.", 409); if (!prior) this.receiptUses.set(receipt.receiptId, { fingerprint, expiresAt: receipt.expiresAt }); try { const result = await this.service.submitControlledObservation(context, { agreementId, versionId, evidenceRequirementId: requirementId, criterionIds: criteria, sourceConstraintId, fixtureId: receipt.fixtureId, displayLabel: "Approved synthetic fixture", capturedAt: receipt.capturedAt, ...(input.observedAt ? { observedAt: text(input, "observedAt") } : {}), metadata, contentDigest: receipt.digest }, text(input, "idempotencyKey"), fingerprint); this.record(context, "hmm_submit_source_observation", input, result, { policyVersion: document.verificationPolicy.policyVersion }); return result; } catch (error) { if (!prior) this.receiptUses.delete(receipt.receiptId); throw error; } }
  async requestAssessment(context: RequestContext, raw: unknown) { const input = strict(raw, ["contractVersion", "agreementId", "versionId", "criterionIds", "idempotencyKey"]); contract(input); const agreementId = text(input, "agreementId"), versionId = text(input, "versionId"); if (input.criterionIds !== undefined) strings(input, "criterionIds"); const { document } = await this.agreement(context, agreementId, versionId); const adapter = new DeterministicAssessmentAdapter(); const result = await this.service.requestControlledAssessment(context, agreementId, versionId, adapter, text(input, "idempotencyKey"), hash(input)); this.record(context, "hmm_request_assessment", input, result, { policyVersion: document.verificationPolicy.policyVersion, providerKind: adapter.providerKind, providerVersion: adapter.providerVersion, adapterVersion: adapter.version, promptVersion: "structured-deterministic-v1", modelVersion: "none", evidenceSetId: result.resource.evidenceSetId }); return result; }
  async requestReview(context: RequestContext, raw: unknown) { const input = strict(raw, ["contractVersion", "agreementId", "versionId", "assessmentId", "evidenceSetId", "reasonCodes", "affectedCriterionIds", "idempotencyKey"]); contract(input); const result = await this.service.requestHumanReview(context, text(input, "agreementId"), text(input, "versionId"), { ...(input.assessmentId ? { assessmentId: text(input, "assessmentId") } : {}), ...(input.evidenceSetId ? { evidenceSetId: text(input, "evidenceSetId") } : {}), reasonCodes: strings(input, "reasonCodes", 10) as ReviewReason[], affectedCriterionIds: strings(input, "affectedCriterionIds", 100) }, text(input, "idempotencyKey"), hash(input)); this.record(context, "hmm_request_human_review", input, result); return result; }
}
