import assert from "node:assert/strict";
import test from "node:test";
import { InMemoryAccountRepository, InMemorySessionRepository } from "../server/auth/in-memory.ts";
import { AuthenticationService } from "../server/auth/service.ts";
import { assertAuthModeAllowed } from "../server/auth/composition.ts";
import { selectPersistenceAdapter } from "../server/persistence/prisma-client.ts";
const account = { accountId: "account-test", state: "active" as const, displayName: "Test Person", createdAt: "2026-08-06T00:00:00.000Z", updatedAt: "2026-08-06T00:00:00.000Z" };
function harness() { let now = new Date("2026-08-06T12:00:00.000Z"); let sequence = 0; const sessions = new InMemorySessionRepository(); const service = new AuthenticationService(new InMemoryAccountRepository([account], new Map([["test", account.accountId]])), sessions, () => now, () => `token-${++sequence}-${"x".repeat(32)}`, () => `session-${sequence}`, { idleMs: 1_000, absoluteMs: 5_000, renewalWindowMs: 200 }); return { service, sessions, advance(ms: number) { now = new Date(now.getTime() + ms); } }; }
test("development sign-in stores digests, issues unrelated secrets, and rotates without fixation", async () => { const { service, sessions } = harness(); const first = await service.signInDevelopment("test"); assert.notEqual(first.token, first.csrfToken); assert.doesNotMatch(JSON.stringify(sessions.recordsForTest()), new RegExp(first.token)); const second = await service.signInDevelopment("test", first.token); assert.equal((await service.resolve(first.token)).context.principal.kind, "anonymous"); assert.equal((await service.resolve(second.token)).context.principal.kind, "account"); assert.equal(second.record.rotation, 1); });
test("missing, malformed, unknown, expired, revoked, and mismatched CSRF values fail closed", async () => { const { service, advance } = harness(); assert.equal((await service.resolve(undefined)).context.principal.kind, "anonymous"); assert.equal((await service.resolve("x".repeat(257))).context.principal.kind, "anonymous"); assert.equal((await service.resolve("unknown")).context.principal.kind, "anonymous"); const signedIn = await service.signInDevelopment("test"); assert.equal(service.verifySessionCsrf("wrong", signedIn.record.csrfDigest), false); assert.equal(service.verifySessionCsrf(signedIn.csrfToken, signedIn.record.csrfDigest), true); advance(1_001); assert.equal((await service.resolve(signedIn.token)).context.principal.kind, "anonymous"); const active = await service.signInDevelopment("test"); await service.signOut(active.token); assert.equal((await service.resolve(active.token)).context.principal.kind, "anonymous"); });
test("login CSRF is single-purpose and unknown local profiles fail generically", async () => { const { service } = harness(); const csrf = service.issuePreAuthenticationCsrf(); assert.equal(service.verifyPreAuthenticationCsrf(csrf.raw, csrf.digest), true); assert.equal(service.verifyPreAuthenticationCsrf("wrong", csrf.digest), false); await assert.rejects(() => service.signInDevelopment("unknown"), /SIGN_IN_FAILED/); });
test("production cannot explicitly select local development authentication", () => { assert.throws(() => assertAuthModeAllowed("production", "local_development"), /cannot run in production/); assert.doesNotThrow(() => assertAuthModeAllowed("test", "local_development")); });
test("persistence selection is explicit and production fails closed", () => { assert.equal(selectPersistenceAdapter("test", undefined), "in_memory"); assert.equal(selectPersistenceAdapter("development", "prisma"), "prisma"); assert.throws(() => selectPersistenceAdapter("development", "unknown"), /must be/); assert.throws(() => selectPersistenceAdapter("production", undefined), /durable/); });
