import assert from "node:assert/strict";
import test from "node:test";
import type { AgreementLanguageDocument } from "../lib/agreement-language/types.ts";
import type { RequestContext } from "../server/agreements/application/contracts.ts";
import { DeterministicAssessmentAdapter, ManualAssessmentAdapter } from "../server/evidence/adapter.ts";
import { evidenceSetDigest, requirementState } from "../server/evidence/domain.ts";
import { InMemoryWorkflowRepository } from "../server/evidence/in-memory-repository.ts";
import { EvidenceAssessmentService } from "../server/evidence/service.ts";
import { EvidenceError } from "../server/evidence/validation.ts";
import type { DevelopmentAssessmentProviderSelector } from "../server/evidence/development-provider.ts";

const stamp = "2026-08-06T18:00:00.000Z";
const document = (): AgreementLanguageDocument => ({
  schemaVersion: "1.0", agreementId: "agreement-1", agreementVersion: 1, versionId: "version-1", versionState: "accepted", economicSides: [],
  purpose: { title: "Verify a commitment", description: "Synthetic local workflow.", plainLanguageSummary: "Evidence is reviewed against one criterion." },
  parties: [{ partyId: "party-submit", partyType: "person", displayName: "Submitter", roles: ["performer"], responsibilityObligationIds: [], acceptanceRequired: true }, { partyId: "party-review", partyType: "person", displayName: "Reviewer", roles: ["reviewer"], responsibilityObligationIds: [], acceptanceRequired: true }],
  terms: { obligations: [], conditions: [], successCriteria: [{ criterionId: "criterion-1", statement: "Synthetic result is true.", evaluationMode: "deterministic", conditionIds: [], evidenceRequirementIds: ["requirement-1"], allowedResults: ["satisfied", "not_satisfied", "indeterminate"] }], deadlines: [] },
  evidencePolicy: { sourceConstraints: [{ sourceConstraintId: "fixture-source", category: "synthetic", retrievalMethod: "participant_submission", permittedFields: ["result", "note"], participantConfirmationRequired: true }], evidenceRequirements: [{ evidenceRequirementId: "requirement-1", criterionIds: ["criterion-1"], importance: "required", evidenceClass: "participant_claim", submitterPartyIds: ["party-submit"], sourceConstraintIds: ["fixture-source"], minimumDistinctSources: 1, independentSourcesRequired: false, visibility: "participants", sensitivity: "standard", onMissing: "request_evidence", onConflict: "request_human_review" }] },
  verificationPolicy: { criterionIds: ["criterion-1"], aggregation: "all_required", policyVersion: "verification-1", missingEvidenceResult: "indeterminate", conflictingEvidenceResult: "indeterminate", mandatoryReviewTriggers: ["low_or_unassessed_confidence", "participant_challenge"], reviewRoute: "local-authorized-review" },
  protectionPolicy: { mode: "none" }, authorizationPolicy: { requirements: [], aiMayAuthorize: false }, resolutionPolicy: { outcomes: [], reviewWindowSeconds: 86400, cancellation: { beforeAcceptance: "creator_may_withdraw", afterAcceptance: "required_party_consent", eligibleInitiatorPartyIds: ["party-submit"] }, maxAppeals: 1 }, privacyPolicy: { defaultEvidenceVisibility: "participants_and_authorized_reviewers", privateEvidenceTrainingUse: false }, financialSafetyPolicy: { initialState: "clear", hooks: [], complianceHoldOverridesTimers: true }, createdAt: stamp, createdByPartyId: "party-submit"
});
const submitter: RequestContext = { principal: { kind: "account", accountId: "account-submit", sessionId: "session-submit", accountState: "active", assurance: "development" }, requestId: "request-1", correlationId: "correlation-1", source: "test" };
const reviewer: RequestContext = { ...submitter, principal: { kind: "account", accountId: "account-review", sessionId: "session-review", accountState: "active", assurance: "development" } };
function harness(accepted = ["party-submit", "party-review"], reviewerPartyId = "party-review") { let id = 0; const repository = new InMemoryWorkflowRepository(); repository.seedAgreement({ document: document(), acceptedPartyIds: accepted, memberships: [{ agreementId: "agreement-1", accountId: "account-submit", partyId: "party-submit", role: "participant", state: "active", createdAt: stamp, createdByAccountId: "account-submit" }, { agreementId: "agreement-1", accountId: "account-review", partyId: reviewerPartyId, role: "reviewer", state: "active", createdAt: stamp, createdByAccountId: "account-submit" }] }); return { repository, service: new EvidenceAssessmentService(repository, () => new Date(stamp), (kind) => `${kind}-${++id}`) }; }
const input = { agreementId: "agreement-1", versionId: "version-1", evidenceRequirementId: "requirement-1", criterionIds: ["criterion-1"], sourceConstraintId: "fixture-source", sourceRefKind: "fixture" as const, sourceRef: "fixture-result-1", sourceDisplayLabel: "Synthetic result", capturedAt: stamp, evidenceClass: "participant_claim" as const, origin: "participant" as const, integrity: "verified" as const, metadata: { result: true, note: "synthetic" } };

test("submission proves exact acceptance, validates safe references, and replays without response bodies", async () => { const { service } = harness(); const first = await service.submitEvidence(submitter, input, "submit-1", "same"); const replay = await service.submitEvidence(submitter, input, "submit-1", "same"); assert.equal(replay.kind, "replayed"); assert.equal(replay.resource.evidenceId, first.resource.evidenceId); await assert.rejects(() => service.submitEvidence(submitter, input, "submit-1", "different"), (error: unknown) => error instanceof EvidenceError && error.code === "IDEMPOTENCY_KEY_REUSED"); const unaccepted = harness(["party-submit"]); await assert.rejects(() => unaccepted.service.submitEvidence(submitter, input, "key", "fp"), /not found/i); await assert.rejects(() => service.submitEvidence(submitter, { ...input, sourceRefKind: "https_url", sourceRef: "https://user:secret@example.test/#fragment" }, "bad", "bad"), (error: unknown) => error instanceof EvidenceError && error.code === "SOURCE_NOT_ALLOWED"); await assert.rejects(() => service.submitEvidence(submitter, { ...input, metadata: { secretToken: "do-not-store" } }, "bad-metadata", "bad"), (error: unknown) => error instanceof EvidenceError && error.code === "METADATA_FIELD_NOT_PERMITTED"); });

test("corrections append immutable revisions and use CAS", async () => { const { service } = harness(); const first = await service.submitEvidence(submitter, input, "submit", "submit"); const corrected = await service.correctEvidence(submitter, "agreement-1", first.resource.evidenceId, 1, { ...input, criterionIds: ["criterion-1"], sourceRef: "fixture-result-2", metadata: { result: false } }, "correct", "correct"); assert.equal(corrected.resource.revision, 2); assert.equal(corrected.resource.currentRevision.supersedesRevisionId, first.resource.currentRevisionId); assert.equal(first.resource.currentRevision.metadata.result, true); const history = await service.getEvidence(submitter, "agreement-1", first.resource.evidenceId); assert.deepEqual(history.revisions.map((revision) => revision.revisionNumber), [2, 1]); assert.equal(history.revisions[1]?.metadata.result, true); await assert.rejects(() => service.correctEvidence(submitter, "agreement-1", first.resource.evidenceId, 1, { ...input, criterionIds: ["criterion-1"] }, "race", "race"), (error: unknown) => error instanceof EvidenceError && error.code === "EVIDENCE_VERSION_CONFLICT"); });

test("workflow context exposes accepted-version role boundaries and requirement reasons", async () => { const { service } = harness(); const context = await service.workflowContext(submitter, "agreement-1", "version-1"); assert.equal(context.acceptedAgreementVersion, 1); assert.equal(context.role, "participant"); assert.equal(context.canSubmitEvidence, true); assert.equal(context.canAssignReview, false); assert.deepEqual(context.requirementStates, [{ evidenceRequirementId: "requirement-1", state: "missing", reasons: ["NO_ELIGIBLE_EVIDENCE"] }]); });

test("assessment capability pins the accepted version and frozen evidence digest", async () => { const { service } = harness(); const gap = await service.getAssessmentCapability(submitter, "agreement-1", "version-1"); assert.equal(gap.status, "eligible_with_gaps"); assert.equal(gap.providerClass, "local_deterministic"); assert.equal(gap.evidenceRevisionCount, 0); await service.submitEvidence(submitter, input, "capability-submit", "capability-submit"); const ready = await service.getAssessmentCapability(submitter, "agreement-1", "version-1"); assert.equal(ready.status, "eligible"); assert.equal(ready.canRequest, true); assert.match(ready.documentDigest, /^[a-f0-9]{64}$/); assert.match(ready.evidenceSetDigest!, /^[a-f0-9]{64}$/); });

test("same immutable assessment envelope coalesces and keeps deterministic provenance", async () => { const { service } = harness(); await service.submitEvidence(submitter, input, "coalesce-submit", "coalesce-submit"); const first = await service.requestAssessment(submitter, "agreement-1", "version-1", new DeterministicAssessmentAdapter(), "coalesce-a", "coalesce-a"); const duplicate = await service.requestAssessment(submitter, "agreement-1", "version-1", new DeterministicAssessmentAdapter(), "coalesce-b", "coalesce-b"); assert.equal(duplicate.kind, "replayed"); assert.equal(duplicate.resource.assessmentId, first.resource.assessmentId); assert.equal(duplicate.resource.providerClass, "local_deterministic"); assert.equal(duplicate.resource.modelVersion, "none"); assert.equal(duplicate.resource.authoritySafe, true); assert.equal(duplicate.resource.semanticExpectationMatched, "not_applicable"); });

test("requirement states retain reasons and canonical evidence-set digests reproduce", () => { const base = { ...input, evidenceRevisionId: "revision-a", evidenceId: "evidence-a", revisionNumber: 1, agreementId: "agreement-1", versionId: "version-1", submittedByPartyId: "party-submit", submittedByAccountId: "account-submit", receivedAt: stamp, availability: "available" as const, validation: "valid" as const, validationReasons: [] }; assert.deepEqual(evidenceSetDigest("agreement-1", "version-1", ["b", "a", "a"]), evidenceSetDigest("agreement-1", "version-1", ["a", "b"])); const state = requirementState([{ ...base, metadata: { result: true } }, { ...base, evidenceRevisionId: "revision-b", evidenceId: "evidence-b", sourceRef: "fixture-result-2", metadata: { result: false } }], 3, true); assert.equal(state.state, "conflicting"); assert.deepEqual(state.reasons, ["CONFLICTING_EVIDENCE", "MINIMUM_SOURCES_UNMET", "SOURCE_INDEPENDENCE_UNPROVEN"]); });

test("assessments remain advisory and reviewer decisions require assignment and prevent self-review", async () => { const { repository, service } = harness(); const evidence = await service.submitEvidence(submitter, input, "submit", "submit"); const assessment = await service.requestAssessment(submitter, "agreement-1", "version-1", new DeterministicAssessmentAdapter(), "assessment", "assessment"); assert.equal(assessment.resource.criterionFindings[0]?.result, "satisfied"); assert.match(assessment.resource.limitations.join(" "), /no decision or settlement authority/i); const set = repository.getEvidenceSetForTest(assessment.resource.evidenceSetId); assert.deepEqual(set?.evidenceRevisionIds, [evidence.resource.currentRevisionId]); const manual = await service.requestAssessment(submitter, "agreement-1", "version-1", new ManualAssessmentAdapter(assessment.resource.criterionFindings), "manual", "manual"); assert.equal(manual.resource.confidence.level, "not_assessed"); const request = await service.requestHumanReview(submitter, "agreement-1", "version-1", { assessmentId: assessment.resource.assessmentId, evidenceSetId: assessment.resource.evidenceSetId, reasonCodes: ["participant_challenge"], affectedCriterionIds: ["criterion-1"] }, "review", "review"); await assert.rejects(() => service.recordReviewerDecision(reviewer, "agreement-1", request.resource.reviewRequestId, 1, { evidenceSetId: assessment.resource.evidenceSetId, evidenceRevisionIds: [evidence.resource.currentRevisionId], assessmentIds: [assessment.resource.assessmentId], decisionType: "record_indeterminate", criterionFindings: [], explanation: "Not assigned.", limitations: [] }, "decision", "decision"), /not found/i); const assigned = await service.assignReview(reviewer, "agreement-1", request.resource.reviewRequestId, 1); const decision = await service.recordReviewerDecision(reviewer, "agreement-1", request.resource.reviewRequestId, assigned.revision, { evidenceSetId: assessment.resource.evidenceSetId, evidenceRevisionIds: [evidence.resource.currentRevisionId], assessmentIds: [assessment.resource.assessmentId], decisionType: "confirm_assessment", criterionFindings: assessment.resource.criterionFindings, explanation: "Reviewed synthetic evidence.", limitations: ["No settlement authority."] }, "decision-2", "decision-2"); assert.equal(decision.resource.authorityBasis, "active_assigned_reviewer_membership"); assert.equal(repository.getDecisionsForTest().length, 1); assert.deepEqual((await service.listReviewerDecisions(reviewer, "agreement-1", "version-1")).map((item) => item.reviewerDecisionId), [decision.resource.reviewerDecisionId]); });

test("reviewer cannot decide their own challenged evidence", async () => { const { service } = harness(["party-submit", "party-review"], "party-submit"); const evidence = await service.submitEvidence(reviewer, input, "submit", "submit"); const request = await service.requestHumanReview(reviewer, "agreement-1", "version-1", { reasonCodes: ["participant_challenge"], affectedCriterionIds: ["criterion-1"] }, "review", "review"); const assigned = await service.assignReview(reviewer, "agreement-1", request.resource.reviewRequestId, 1); await assert.rejects(() => service.recordReviewerDecision(reviewer, "agreement-1", request.resource.reviewRequestId, assigned.revision, { evidenceRevisionIds: [evidence.resource.currentRevisionId], assessmentIds: [], decisionType: "record_indeterminate", criterionFindings: [], explanation: "Review.", limitations: [] }, "decision", "decision"), (error: unknown) => error instanceof EvidenceError && error.code === "EVIDENCE_NOT_ALLOWED"); });

test("completed OpenAI provenance survives orchestrator, service, and persistence without stale policy fallback", async () => {
  const { repository } = harness(); let id = 100;
  const provider = { kind: "model" as const, version: "guard-wrapper-v1", providerKind: "future_model" as const, providerVersion: "openai-v1", async evaluate(adapterInput: Parameters<DeterministicAssessmentAdapter["evaluate"]>[0]) { return { findings: [{ criterionId: "criterion-1", result: "satisfied" as const, supportingEvidenceRevisionIds: [adapterInput.evidence[0]!.evidenceRevisionId], conflictingEvidenceRevisionIds: [], evidenceRequirementIds: ["requirement-1"], explanation: "Synthetic result.", limitations: [] }], confidence: { level: "high" as const, basis: ["Synthetic fixture."], limitations: [] }, limitations: ["Advisory only."], recommendedNextAction: "no_action" as const }; }, completedRunProvenance: () => ({ providerName: "openai" as const, providerClass: "development_model" as const, adapterVersion: "openai-adapter-v2", requestedModelVersion: "requested-model-v1", resolvedModelVersion: "resolved-model-v1", modelVersion: "resolved-model-v1", promptVersion: "prompt-live-v2", schemaVersion: "schema-live-v2", policyVersion: "policy-live-v2", configurationDigest: "a".repeat(64), authorizationId: "authorization-live", attemptId: "attempt-live", runId: "run-live", correlationId: "correlation-live" }) };
  const selector = { select: () => ({ provider, requestedProvider: "openai" as const }), capability: () => ({ providerClass: "development_model" as const, providerLabel: "OpenAI development assessment", budgetState: "available" as const, reasonCodes: [] }) } as unknown as DevelopmentAssessmentProviderSelector;
  const service = new EvidenceAssessmentService(repository, () => new Date(stamp), (kind) => `${kind}-${++id}`, selector); await service.submitEvidence(submitter, input, "model-submit", "model-submit"); const result = await service.requestProductAssessment(submitter, "agreement-1", "version-1", "model-assessment", "model-assessment");
  assert.equal(result.resource.providerName, "openai"); assert.equal(result.resource.adapterVersion, "openai-adapter-v2"); assert.equal(result.resource.requestedModelVersion, "requested-model-v1"); assert.equal(result.resource.resolvedModelVersion, "resolved-model-v1"); assert.equal(result.resource.modelVersion, "resolved-model-v1"); assert.equal(result.resource.policyVersion, "policy-live-v2"); assert.equal(result.resource.browserAuthorizationId, "authorization-live"); assert.equal(result.resource.browserAttemptId, "attempt-live"); assert.equal(result.resource.authoritySafe, true); assert.doesNotMatch(JSON.stringify(result.resource), /api.?key|raw.?prompt|raw.?response|request.?body|response.?body/i);
});
