import assert from "node:assert/strict";
import test from "node:test";
import type { AgreementLanguageDocument } from "../lib/agreement-language/types.ts";
import { InMemoryWorkflowRepository } from "../server/evidence/in-memory-repository.ts";
import { EvidenceAssessmentService } from "../server/evidence/service.ts";
import { VerificationFacade } from "../server/mcp/facade.ts";
import { TOOL_NAMES, ToolRegistry } from "../server/mcp/registry.ts";
import { actorContext, InvocationGuard, issueActorToken, issueReceipt, verifyReceipt } from "../server/mcp/security.ts";
import { LocalMcpServer } from "../server/mcp/server.ts";

const stamp = "2026-08-06T18:00:00.000Z"; const epoch = Date.parse(stamp) / 1000; const secret = "local-test-secret-that-is-at-least-32-characters";
const document = (sensitivity: "standard" | "sensitive" = "standard"): AgreementLanguageDocument => ({ schemaVersion: "1.0", agreementId: "agreement-1", agreementVersion: 1, versionId: "version-1", versionState: "accepted", economicSides: [], purpose: { title: "Verify", description: "Synthetic local verification.", plainLanguageSummary: "Check one typed result." }, parties: [{ partyId: "party-submit", partyType: "person", displayName: "Submitter", roles: ["performer"], responsibilityObligationIds: [], acceptanceRequired: true }, { partyId: "party-review", partyType: "person", displayName: "Reviewer", roles: ["reviewer"], responsibilityObligationIds: [], acceptanceRequired: true }], terms: { obligations: [], conditions: [], successCriteria: [{ criterionId: "criterion-1", statement: "The result is true.", evaluationMode: "deterministic", conditionIds: [], evidenceRequirementIds: ["requirement-1"], allowedResults: ["satisfied", "not_satisfied", "indeterminate"] }], deadlines: [] }, evidencePolicy: { sourceConstraints: [{ sourceConstraintId: "fixture-source", category: "synthetic", retrievalMethod: "authorized_read", permittedFields: ["result", "note"], participantConfirmationRequired: true }], evidenceRequirements: [{ evidenceRequirementId: "requirement-1", criterionIds: ["criterion-1"], importance: "required", evidenceClass: "participant_claim", submitterPartyIds: ["party-submit"], sourceConstraintIds: ["fixture-source"], minimumDistinctSources: 1, independentSourcesRequired: false, visibility: "participants", sensitivity, onMissing: "request_evidence", onConflict: "request_human_review" }] }, verificationPolicy: { criterionIds: ["criterion-1"], aggregation: "all_required", policyVersion: "verification-1", missingEvidenceResult: "indeterminate", conflictingEvidenceResult: "indeterminate", mandatoryReviewTriggers: ["low_or_unassessed_confidence", "participant_challenge"], reviewRoute: "local-authorized-review" }, protectionPolicy: { mode: "none" }, authorizationPolicy: { requirements: [], aiMayAuthorize: false }, resolutionPolicy: { outcomes: [], reviewWindowSeconds: 86400, cancellation: { beforeAcceptance: "creator_may_withdraw", afterAcceptance: "required_party_consent", eligibleInitiatorPartyIds: ["party-submit"] }, maxAppeals: 1 }, privacyPolicy: { defaultEvidenceVisibility: "participants_and_authorized_reviewers", privateEvidenceTrainingUse: false }, financialSafetyPolicy: { initialState: "clear", hooks: [], complianceHoldOverridesTimers: true }, createdAt: stamp, createdByPartyId: "party-submit" });
function harness(sensitivity: "standard" | "sensitive" = "standard") { let id = 0; const repository = new InMemoryWorkflowRepository(); repository.seedAgreement({ document: document(sensitivity), acceptedPartyIds: ["party-submit", "party-review"], memberships: [{ agreementId: "agreement-1", accountId: "account-submit", partyId: "party-submit", role: "participant", state: "active", createdAt: stamp, createdByAccountId: "account-submit" }] }); const service = new EvidenceAssessmentService(repository, () => new Date(stamp), (kind) => `${kind}-${++id}`); const facade = new VerificationFacade(repository, service, secret, () => new Date(stamp)); const server = new LocalMcpServer(new ToolRegistry(facade), secret, () => new Date(stamp)); const token = issueActorToken({ accountId: "account-submit", sessionId: "session-submit", audience: "hmm-local-mcp", purpose: "verification", issuedAt: epoch - 10, expiresAt: epoch + 300 }, secret); const call = async (name: string, args: Record<string, unknown>, actorToken = token) => server.handle({ jsonrpc: "2.0", id: 1, method: "tools/call", params: { name, arguments: { contractVersion: "2026-08-06", ...args }, actorToken } }); return { facade, server, token, call }; }
const base = { agreementId: "agreement-1", versionId: "version-1" };

test("registry is a static verification-only allowlist and denies authority, settlement, URL, shell, browser, filesystem, and database capabilities", async () => { const { call } = harness(); assert.deepEqual(TOOL_NAMES, ["hmm_get_agreement_terms", "hmm_get_evidence_requirements", "hmm_list_evidence_metadata", "hmm_get_assessment", "hmm_retrieve_approved_source", "hmm_submit_source_observation", "hmm_request_assessment", "hmm_request_human_review"]); for (const name of ["record_resolution", "grant_authorization", "assign_reviewer", "record_reviewer_decision", "transition_financial_safety", "create_settlement_instruction", "execute_settlement", "fetch_url", "shell", "browser", "filesystem", "prisma_query"]) { const response = await call(name, base) as { error: { data: { code: string } } }; assert.equal(response.error.data.code, "TOOL_NOT_ALLOWED"); } });

test("signed short-lived actor context rejects expiry and audience escalation", () => { const expired = issueActorToken({ accountId: "account-submit", sessionId: "session", audience: "hmm-local-mcp", purpose: "verification", issuedAt: epoch - 400, expiresAt: epoch - 100 }, secret); assert.throws(() => actorContext(expired, secret, epoch, "request"), /authentication/i); const tampered = `${issueActorToken({ accountId: "account-submit", sessionId: "session", audience: "hmm-local-mcp", purpose: "verification", issuedAt: epoch, expiresAt: epoch + 100 }, secret)}x`; assert.throws(() => actorContext(tampered, secret, epoch, "request"), /authentication/i); });

test("controlled fixture receipt drives an idempotent observation, deterministic advisory assessment, and scoped human-review request", async () => { const { call, facade } = harness(); const retrieved = await call("hmm_retrieve_approved_source", { ...base, sourceConstraintId: "fixture-source", fixtureId: "fixture.result.true", fields: ["result", "note"] }) as { result: { structuredContent: { observation: object; capturedAt: string; retrievalReceiptId: string } } }; const source = retrieved.result.structuredContent; const submitted = await call("hmm_submit_source_observation", { ...base, evidenceRequirementId: "requirement-1", criterionIds: ["criterion-1"], sourceConstraintId: "fixture-source", retrievalReceiptId: source.retrievalReceiptId, metadata: source.observation, capturedAt: source.capturedAt, idempotencyKey: "observation-1" }) as { result: { structuredContent: { kind: string } } }; assert.equal(submitted.result.structuredContent.kind, "created"); const replay = await call("hmm_submit_source_observation", { ...base, evidenceRequirementId: "requirement-1", criterionIds: ["criterion-1"], sourceConstraintId: "fixture-source", retrievalReceiptId: source.retrievalReceiptId, metadata: source.observation, capturedAt: source.capturedAt, idempotencyKey: "observation-1" }) as { result: { structuredContent: { kind: string } } }; assert.equal(replay.result.structuredContent.kind, "replayed"); const assessment = await call("hmm_request_assessment", { ...base, idempotencyKey: "assessment-1" }) as { result: { structuredContent: { resource: { assessmentId: string; evidenceSetId: string; adapterKind: string; limitations: string[] } } } }; const advisory = assessment.result.structuredContent.resource; assert.equal(advisory.adapterKind, "deterministic"); assert.match(advisory.limitations.join(" "), /no decision or settlement authority/i); const review = await call("hmm_request_human_review", { ...base, assessmentId: advisory.assessmentId, evidenceSetId: advisory.evidenceSetId, reasonCodes: ["participant_challenge"], affectedCriterionIds: ["criterion-1"], idempotencyKey: "review-1" }) as { result: { structuredContent: { resource: { state: string; assignedAccountId?: string } } } }; assert.equal(review.result.structuredContent.resource.state, "open"); assert.equal(review.result.structuredContent.resource.assignedAccountId, undefined); assert.ok(facade.provenance.some((event) => event.adapterVersion === "deterministic-v1" && event.promptVersion === "structured-deterministic-v1" && event.modelVersion === "none" && event.evidenceSetId)); assert.ok(facade.provenance.every((event) => !JSON.stringify(event).includes("UNTRUSTED CONTENT"))); });

test("malicious input, arbitrary URLs, receipt scope changes, adapter selection, prompt injection, and cross-scope review references fail safely", async () => { const { call } = harness(); const url = await call("hmm_retrieve_approved_source", { ...base, sourceConstraintId: "fixture-source", fixtureId: "https://example.test/private", fields: ["result"] }) as { error: { data: { code: string } } }; assert.equal(url.error.data.code, "SOURCE_NOT_ALLOWED"); const adapter = await call("hmm_request_assessment", { ...base, adapterKind: "manual", findings: [], idempotencyKey: "bad" }) as { error: { data: { code: string } } }; assert.equal(adapter.error.data.code, "INVALID_REQUEST"); const injected = await call("hmm_retrieve_approved_source", { ...base, sourceConstraintId: "fixture-source", fixtureId: "fixture.prompt.injection", fields: ["result", "note"] }) as { result: { structuredContent: { observation: Record<string, unknown>; capturedAt: string; retrievalReceiptId: string } } }; assert.match(String(injected.result.structuredContent.observation.note), /execute settlement/); const scoped = await call("hmm_submit_source_observation", { ...base, agreementId: "other-agreement", evidenceRequirementId: "requirement-1", criterionIds: ["criterion-1"], sourceConstraintId: "fixture-source", retrievalReceiptId: injected.result.structuredContent.retrievalReceiptId, metadata: injected.result.structuredContent.observation, capturedAt: injected.result.structuredContent.capturedAt, idempotencyKey: "bad-scope" }) as { error: { data: { code: string } } }; assert.equal(scoped.error.data.code, "RECEIPT_SCOPE_MISMATCH"); const review = await call("hmm_request_human_review", { ...base, assessmentId: "assessment-other", evidenceSetId: "set-other", reasonCodes: ["participant_challenge"], affectedCriterionIds: ["criterion-1"], idempotencyKey: "bad-review" }) as { error: { data: { code: string } } }; assert.equal(review.error.data.code, "RESOURCE_NOT_FOUND"); });

test("privacy fails closed and request leases reject concurrent matching operations", async () => { const { call } = harness("sensitive"); const requirements = await call("hmm_get_evidence_requirements", base) as { result: { structuredContent: unknown[] } }; assert.deepEqual(requirements.result.structuredContent, []); const assessment = await call("hmm_request_assessment", { ...base, idempotencyKey: "private" }) as { error: { data: { code: string } } }; assert.equal(assessment.error.data.code, "PRIVACY_POLICY_UNENFORCEABLE"); const guard = new InvocationGuard(); const release = guard.enter("actor", "tool", epoch); assert.throws(() => guard.enter("actor", "tool", epoch), /already running/i); release(); assert.doesNotThrow(() => guard.enter("actor", "tool", epoch)()); });

test("actor tokens fail closed across forgery, time, audience, purpose, and actor scope", async () => {
  const { call, token } = harness();
  const claims = (overrides: Record<string, unknown>) => issueActorToken({ accountId: "account-submit", sessionId: "session-submit", audience: "hmm-local-mcp", purpose: "verification", issuedAt: epoch - 10, expiresAt: epoch + 300, ...overrides } as Parameters<typeof issueActorToken>[0], secret);
  for (const invalid of [
    `${token.slice(0, -1)}${token.endsWith("a") ? "b" : "a"}`,
    claims({ issuedAt: epoch + 1, expiresAt: epoch + 301 }),
    claims({ audience: "other-audience" }),
    claims({ purpose: "settlement" }),
  ]) {
    const response = await call("hmm_get_agreement_terms", base, invalid) as { error: { data: { code: string }; message: string } };
    assert.equal(response.error.data.code, "AUTHENTICATION_REQUIRED");
    assert.equal(response.error.message, "Local MCP authentication is required.");
  }
  const otherActor = claims({ accountId: "account-other" });
  const response = await call("hmm_get_agreement_terms", base, otherActor) as { error: { data: { code: string } } };
  assert.equal(response.error.data.code, "RESOURCE_NOT_FOUND");
});

test("receipts reject forgery, expiry, replay mismatch, cross-actor use, and exact scope changes", async () => {
  const { call } = harness();
  const retrieved = await call("hmm_retrieve_approved_source", { ...base, sourceConstraintId: "fixture-source", fixtureId: "fixture.result.true", fields: ["result", "note"] }) as { result: { structuredContent: { observation: object; capturedAt: string; retrievalReceiptId: string } } };
  const source = retrieved.result.structuredContent;
  const submission = { ...base, evidenceRequirementId: "requirement-1", criterionIds: ["criterion-1"], sourceConstraintId: "fixture-source", retrievalReceiptId: source.retrievalReceiptId, metadata: source.observation, capturedAt: source.capturedAt, idempotencyKey: "receipt-scope" };
  const forged = { ...submission, retrievalReceiptId: `${source.retrievalReceiptId}x` };
  assert.equal(((await call("hmm_submit_source_observation", forged)) as { error: { data: { code: string } } }).error.data.code, "RECEIPT_INVALID");
  const otherActor = issueActorToken({ accountId: "account-other", sessionId: "session-other", audience: "hmm-local-mcp", purpose: "verification", issuedAt: epoch - 10, expiresAt: epoch + 300 }, secret);
  assert.equal(((await call("hmm_submit_source_observation", submission, otherActor)) as { error: { data: { code: string } } }).error.data.code, "RECEIPT_SCOPE_MISMATCH");
  assert.equal(((await call("hmm_submit_source_observation", { ...submission, criterionIds: ["criterion-other"] })) as { error: { data: { code: string } } }).error.data.code, "EVIDENCE_INVALID");
  assert.equal(((await call("hmm_submit_source_observation", { ...submission, idempotencyKey: "receipt-scope", metadata: { result: false, note: "changed" } })) as { error: { data: { code: string } } }).error.data.code, "RECEIPT_SCOPE_MISMATCH");
  await call("hmm_submit_source_observation", submission);
  assert.equal(((await call("hmm_submit_source_observation", { ...submission, idempotencyKey: "receipt-reused" })) as { error: { data: { code: string } } }).error.data.code, "RECEIPT_REPLAYED");
  const expired = issueReceipt({ receiptId: "receipt-expired", accountId: "account-submit", agreementId: base.agreementId, versionId: base.versionId, sourceConstraintId: "fixture-source", adapterVersion: "fixture-v1", fixtureId: "fixture.result.true", referenceDigest: "digest", fields: ["result"], capturedAt: stamp, digest: "digest", correlationId: "correlation", issuedAt: epoch - 400, expiresAt: epoch - 100 }, secret);
  assert.throws(() => verifyReceipt(expired, secret, epoch), /invalid or expired/i);
});

test("resource bounds, exact references, and idempotency mismatches fail safely", async () => {
  const { call } = harness();
  assert.equal(((await call("hmm_list_evidence_metadata", { ...base, pageSize: 51 })) as { error: { data: { code: string } } }).error.data.code, "INVALID_REQUEST");
  assert.equal(((await call("hmm_get_agreement_terms", { ...base, versionId: "version-other" })) as { error: { data: { code: string } } }).error.data.code, "RESOURCE_NOT_FOUND");
  await call("hmm_request_assessment", { ...base, idempotencyKey: "same-key" });
  assert.equal(((await call("hmm_request_assessment", { ...base, criterionIds: ["criterion-1"], idempotencyKey: "same-key" })) as { error: { data: { code: string } } }).error.data.code, "IDEMPOTENCY_KEY_REUSED");
  const rate = harness();
  for (let index = 0; index < 60; index += 1) await rate.call("hmm_get_agreement_terms", base);
  assert.equal(((await rate.call("hmm_get_agreement_terms", base)) as { error: { data: { code: string } } }).error.data.code, "RESOURCE_LIMIT");
});
