/* eslint-disable @typescript-eslint/no-explicit-any -- malformed policy fixtures exercise runtime validation. */
import test from "node:test"; import assert from "node:assert/strict";
import { ALLOWED_TRANSITIONS, balancedEntries, canTransition, consequenceRef, evaluateResolutionReadiness, explicitRequirement, validateEffect, type ReadinessSnapshot } from "../server/resolution/domain.ts";
const now = new Date("2026-08-15T00:00:00.000Z");
const document = (overrides: Record<string, unknown> = {}) => ({ versionId: "version-1", versionState: "accepted", parties: [{ partyId: "party-a", partyType: "person", acceptanceRequired: true }, { partyId: "party-b", partyType: "person", acceptanceRequired: true }], economicSides: [{ economicSideId: "side-a", partyIds: ["party-a"], settlementDestinationRef: "destination-a" }, { economicSideId: "side-b", partyIds: ["party-b"], settlementDestinationRef: "destination-b" }], protectionPolicy: { mode: "protection", terms: { money: { amountMinor: 2500, currency: "CAD" } } }, authorizationPolicy: { aiMayAuthorize: false, requirements: [{ action: "record_resolution", eligiblePartyIds: ["party-a"], minimumApprovals: 1, selfApprovalProhibited: false, requiredVersionState: ["accepted"], humanReviewRequired: false }, { action: "create_settlement_instruction", eligiblePartyIds: ["party-a", "party-b"], minimumApprovals: 1, selfApprovalProhibited: false, requiredVersionState: ["accepted"], humanReviewRequired: false }] }, resolutionPolicy: { reviewWindowSeconds: 3600, outcomes: [{ outcomeId: "complete" }] }, ...overrides }) as any;
const snapshot = (): ReadinessSnapshot => ({ state: "authorized", versionId: "version-1", document: document(), documentDigest: "digest", expectedDocumentDigest: "digest", acceptedPartyIds: ["party-a", "party-b"], outcomeId: "complete", consequenceRef: "ref", effect: { kind: "simulated_value", amountMinor: 2500, currency: "CAD", sourceEconomicSideId: "side-a", destinationEconomicSideId: "side-b", destinationRef: "destination-b" }, assessment: { status: "completed", results: ["satisfied"], recommendedNextAction: "participant_review" }, reviewerDecisionPresent: false, reviewWindowEndsAt: "2026-08-14T23:59:59.000Z", activeDispute: false, financialSafetyState: "clear", grants: [{ partyId: "party-b", action: "create_settlement_instruction", consequenceRef: "ref", grantedAt: "2026-08-14T00:00:00.000Z" }], priorExecution: false, createdByPartyId: "party-a" });
test("lifecycle table keeps terminal states immutable", () => { assert.deepEqual(ALLOWED_TRANSITIONS.simulated_executed, []); assert.deepEqual(ALLOWED_TRANSITIONS.cancelled, []); assert.deepEqual(ALLOWED_TRANSITIONS.expired, []); for (const terminal of ["simulated_executed", "cancelled", "expired"] as const) assert.equal(canTransition(terminal, "held"), false); assert.ok(canTransition("disputed", "held")); });
test("missing or ambiguous record_resolution authority is rejected", () => { const missing = document(); missing.authorizationPolicy.requirements = missing.authorizationPolicy.requirements.filter((x: any) => x.action !== "record_resolution"); assert.equal(explicitRequirement(missing, "record_resolution"), null); const ambiguous = document(); ambiguous.authorizationPolicy.requirements.push({ ...ambiguous.authorizationPolicy.requirements[0] }); assert.equal(explicitRequirement(ambiguous, "record_resolution"), null); });
test("review window boundary is exact and Financial Safety has precedence", () => { const active = snapshot(); active.reviewWindowEndsAt = "2026-08-15T00:00:00.001Z"; assert.ok(evaluateResolutionReadiness(active, now).blockers.includes("REVIEW_WINDOW_ACTIVE")); const boundary = snapshot(); assert.equal(evaluateResolutionReadiness(boundary, now).ready, true); for (const state of ["review_required", "held", "restricted"] as const) { const held = snapshot(); held.financialSafetyState = state; const result = evaluateResolutionReadiness(held, now); assert.equal(result.ready, false); assert.ok(result.blockers.some((x) => x.startsWith("FINANCIAL_SAFETY_"))); } });
test("disputes, revoked grants, and missing human review cannot substitute for one another", () => { const value = snapshot(); value.activeDispute = true; value.grants[0]!.revokedAt = "2026-08-14T12:00:00.000Z"; value.document.authorizationPolicy.requirements[1].humanReviewRequired = true; const blockers = evaluateResolutionReadiness(value, now).blockers; assert.ok(blockers.includes("ACTIVE_DISPUTE")); assert.ok(blockers.includes("AUTHORIZATION_REVOKED")); assert.ok(blockers.includes("HUMAN_REVIEW_REQUIRED")); });
test("solo financial and invalid economic sides are prohibited", () => { const solo = document({ economicSides: [{ economicSideId: "side-a", partyIds: ["party-a"] }] }); assert.ok(validateEffect(solo, snapshot().effect).includes("SOLO_FINANCIAL_PROHIBITED")); const circular = snapshot().effect as any; circular.destinationEconomicSideId = "side-a"; assert.ok(validateEffect(document(), circular).includes("ECONOMIC_SIDES_INVALID")); });
test("simulated ledger is exactly balanced and consequence refs are deterministic", () => { const effect = snapshot().effect; const entries = balancedEntries(effect); assert.equal(entries.length, 2); assert.equal(entries.reduce((sum, x) => sum + x.amountMinor, 0), 0); assert.equal(consequenceRef("v", "o", effect), consequenceRef("v", "o", effect)); });
test("expiry is absent unless explicitly supplied and blocks at its exact boundary", () => { const value = snapshot(); assert.equal(value.expiresAt, undefined); value.expiresAt = now.toISOString(); assert.ok(evaluateResolutionReadiness(value, now).blockers.includes("PROPOSAL_EXPIRED")); });
