import { AlertTriangle, Bot, Check, Clock3, FileText, LockKeyhole, UserRound } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { formatDate, formatMoney } from "@/lib/agreements/selectors";
import type { Agreement } from "@/types/agreement";
import { AgreementStatusBadge } from "./AgreementStatusBadge";

export function AgreementDetail({ agreement }: { agreement: Agreement }) { const nav=["overview","terms","participants","evidence","protection","activity","resolution"]; return <>
  <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-950"><strong>Interactive demonstration:</strong> This record uses fixed mock data. Nothing is saved, shared securely, funded, or settled.</div>
  <header className="grid gap-4"><div className="flex flex-wrap items-center gap-3"><AgreementStatusBadge status={agreement.status}/><span className="text-sm text-slate-500">Agreement version {agreement.version}</span></div><h1 className="max-w-4xl text-3xl font-semibold tracking-tight sm:text-4xl">{agreement.title}</h1><p className="max-w-3xl text-lg leading-8 text-slate-600">{agreement.plainLanguageSummary}</p><div className="rounded-xl border-l-4 border-teal-700 bg-white p-4"><p className="text-sm font-semibold text-teal-900">Next action</p><p className="mt-1 text-slate-700">{agreement.nextAction}</p></div></header>
  <nav aria-label="Agreement sections" className="overflow-x-auto border-y py-3"><ul className="flex min-w-max gap-2">{nav.map(id=><li key={id}><a href={`#${id}`} className="inline-flex min-h-10 items-center rounded-lg px-3 text-sm font-medium capitalize text-slate-600 hover:bg-slate-100 focus-visible:outline-2 focus-visible:outline-teal-700">{id}</a></li>)}</ul></nav>
  {agreement.exceptionState && <div role="status" className="flex gap-3 rounded-xl border border-amber-300 bg-amber-50 p-4 text-amber-950"><AlertTriangle aria-hidden="true" className="mt-1 size-5 shrink-0"/><div><h2 className="font-semibold">{agreement.exceptionState.title}</h2><p className="mt-1 text-sm">{agreement.exceptionState.description}</p></div></div>}
  <section id="overview" className="scroll-mt-24"><SectionTitle title="Overview" description="Purpose, timing, and lifecycle at a glance."/><div className="grid gap-4 md:grid-cols-3"><InfoCard label="Purpose" value={agreement.description}/><InfoCard label="Deadline" value={`${formatDate(agreement.deadline)} (UTC)`}/><InfoCard label="Verification" value={agreement.verification.method.replaceAll("_"," ")}/></div><h3 className="mt-8 text-lg font-semibold">Lifecycle</h3><ol className="mt-4 grid gap-3 lg:grid-cols-5">{agreement.timeline.map(event=><li key={event.id} className={`rounded-xl border p-4 ${event.state === "current" ? "border-teal-500 bg-teal-50" : event.state === "exception" ? "border-amber-400 bg-amber-50" : "bg-white"}`}><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">{event.state}</span><p className="mt-2 font-medium">{event.label}</p><p className="mt-1 text-sm leading-6 text-slate-600">{event.description}</p></li>)}</ol></section>
  <section id="terms" className="scroll-mt-24"><SectionTitle title="Terms" description={`Read-only terms for accepted version ${agreement.version}.`}/><Card><CardContent className="grid gap-7 pt-6 md:grid-cols-3"><TermList title="Responsibilities" items={agreement.obligations}/><TermList title="Success conditions" items={agreement.successConditions}/><TermList title="Evidence expectations" items={agreement.evidenceExpectations}/></CardContent></Card></section>
  <section id="participants" className="scroll-mt-24"><SectionTitle title="Participants" description="Roles, responsibilities, and acceptance are shown without personal contact details."/><ul className="grid gap-4 md:grid-cols-2">{agreement.participants.map(p=><li key={p.id}><Card><CardContent className="flex gap-4 pt-6"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-slate-100 font-semibold">{p.initials}</span><div><h3 className="font-semibold">{p.displayName}</h3><p className="text-sm capitalize text-slate-500">{p.role} · {p.acceptanceStatus.replaceAll("_"," ")}</p><p className="mt-2 text-sm leading-6 text-slate-700">{p.responsibilitySummary}</p>{p.acceptedVersion && <p className="mt-2 text-xs text-slate-500">Accepted version {p.acceptedVersion}{p.acceptedAt ? ` on ${formatDate(p.acceptedAt)}` : ""}</p>}</div></CardContent></Card></li>)}</ul></section>
  <section id="evidence" className="scroll-mt-24"><SectionTitle title="Evidence and assessment" description="Participant claims, source records, and AI inference remain visibly distinct."/>{agreement.evidence.length ? <ul className="grid gap-4 md:grid-cols-2">{agreement.evidence.map(e=><li key={e.id}><Card><CardHeader><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-slate-500"><FileText className="size-4" aria-hidden="true"/>Evidence · {e.kind.replaceAll("_"," ")}</div><CardTitle className="text-lg">{e.title}</CardTitle></CardHeader><CardContent className="grid gap-2 text-sm text-slate-600"><p><strong className="text-slate-800">Source:</strong> {e.source}</p><p><strong className="text-slate-800">Submitted by:</strong> {e.submittedBy}</p><p><strong className="text-slate-800">Captured:</strong> {formatDate(e.capturedAt)} (UTC)</p><p><strong className="text-slate-800">Condition:</strong> {e.relatedCriterion}</p></CardContent></Card></li>)}</ul> : <Empty title="No evidence added" text="The agreed evidence expectations are visible in Terms. Evidence collection is not connected in this demo."/>}{agreement.verification.assessment ? <Assessment agreement={agreement}/> : <Empty title="Assessment not ready" text="An assessment appears only after relevant evidence is available. It remains advisory and cannot authorize an outcome."/>}</section>
  <section id="protection" className="scroll-mt-24"><SectionTitle title="Protection" description="Funding is optional and never defines the agreement itself."/><Card><CardContent className="pt-6"><div className="flex items-start gap-3"><LockKeyhole className="mt-1 size-5 shrink-0 text-teal-800" aria-hidden="true"/><div><h3 className="font-semibold">{agreement.funding.mode === "none" ? "No funding protection selected" : agreement.funding.mode === "protection" ? "Simulated funding protection" : "Conditional payment intent"}</h3>{agreement.funding.amountMinor !== undefined && agreement.funding.currency && <p className="mt-2 text-2xl font-semibold tabular-nums">{formatMoney(agreement.funding.amountMinor,agreement.funding.currency)} {agreement.funding.currency}</p>}<p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{agreement.funding.explanation}</p>{agreement.funding.feesMinor !== undefined && agreement.funding.currency && <p className="mt-2 text-sm">Simulated fees: {formatMoney(agreement.funding.feesMinor,agreement.funding.currency)} {agreement.funding.currency}</p>}</div></div></CardContent></Card></section>
  <section id="activity" className="scroll-mt-24"><SectionTitle title="Activity" description="An attributable mock history, not a claim of an immutable audit log."/>{agreement.auditEvents.length ? <ol className="grid gap-3">{agreement.auditEvents.map(e=><li key={e.id} className="flex gap-3 rounded-xl border bg-white p-4"><Clock3 className="mt-1 size-5 shrink-0 text-slate-500" aria-hidden="true"/><div><p><strong>{e.actor}</strong> — {e.summary}</p><p className="mt-1 text-sm text-slate-500">{formatDate(e.occurredAt)} (UTC) · Version {e.agreementVersion} · Source: {e.source.replaceAll("_"," ")}</p></div></li>)}</ol> : <Empty title="No activity yet" text="This draft has not recorded any mock participant activity."/>}</section>
  <section id="resolution" className="scroll-mt-24"><SectionTitle title="Resolution" description="Consequential outcomes require explicit participant authorization or human review."/><Card><CardContent className="grid gap-5 pt-6"><InfoCard label="Expected outcome" value={agreement.resolution.expectedOutcome}/><InfoCard label="Review path" value={agreement.resolution.reviewPath}/>{agreement.resolution.declaredOutcome && <InfoCard label="Declared outcome" value={agreement.resolution.declaredOutcome}/>}<div className="rounded-lg bg-slate-100 p-4 text-sm text-slate-700"><strong>No automatic settlement:</strong> this view has no release, refund, cancellation, or settlement control. A future implementation must verify authorization server-side and preserve a human-review path.</div></CardContent></Card></section>
  </>; }

function SectionTitle({title,description}:{title:string;description:string}) { return <div className="mb-5 mt-10"><h2 className="text-2xl font-semibold">{title}</h2><p className="mt-1 text-slate-600">{description}</p></div>; }
function InfoCard({label,value}:{label:string;value:string}) { return <div className="rounded-xl border bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 leading-6 text-slate-800">{value}</p></div>; }
function TermList({title,items}:{title:string;items:string[]}) { return <div><h3 className="font-semibold">{title}</h3><ul className="mt-3 grid gap-3">{items.map(item=><li key={item} className="flex gap-2 text-sm leading-6 text-slate-700"><Check aria-hidden="true" className="mt-1 size-4 shrink-0 text-teal-700"/>{item}</li>)}</ul></div>; }
function Empty({title,text}:{title:string;text:string}) { return <div className="rounded-xl border border-dashed bg-white p-8 text-center"><h3 className="font-semibold">{title}</h3><p className="mx-auto mt-2 max-w-xl text-sm text-slate-600">{text}</p></div>; }
function Assessment({agreement}:{agreement:Agreement}) { const a=agreement.verification.assessment!; return <Card className="mt-5 border-violet-200"><CardHeader><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-violet-800"><Bot aria-hidden="true" className="size-4"/>Advisory AI assessment</div><CardTitle className="text-xl">{a.confidence[0].toUpperCase()+a.confidence.slice(1)} confidence recommendation</CardTitle></CardHeader><CardContent className="grid gap-5"><p>{a.summary}</p><Separator/><div className="grid gap-5 md:grid-cols-3"><TermList title="Matched criteria" items={a.matchedCriteria}/><TermList title="Missing information" items={a.missingInformation}/><TermList title="Limitations" items={a.limitations}/></div><div className="rounded-lg bg-violet-50 p-4"><p className="font-semibold">Recommended next step</p><p className="mt-1 text-sm leading-6">{a.recommendedAction}</p></div><p className="flex gap-2 text-sm text-slate-600"><UserRound aria-hidden="true" className="mt-0.5 size-4 shrink-0"/>{agreement.verification.reviewRoute}</p></CardContent></Card>; }
