"use client";
import { useState } from "react";
import Link from "next/link";
import { Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { filterAgreements } from "@/lib/agreements/selectors";
import { STATUS_LABELS } from "@/lib/agreements/status";
import type { AgreementSummary } from "@/types/agreement";
import { AgreementCard } from "./AgreementCard";
export function AgreementCollection({ agreements }: { agreements: AgreementSummary[] }) { const [query,setQuery]=useState(""); const [status,setStatus]=useState("all"); const [funding,setFunding]=useState("all"); const filtered=filterAgreements(agreements,query,status,funding); const reset=()=>{setQuery("");setStatus("all");setFunding("all")}; return <div className="grid gap-6"><div className="grid gap-4 rounded-xl border bg-white p-4 lg:grid-cols-[1fr_13rem_13rem_auto] lg:items-end"><label className="grid gap-1.5 text-sm font-medium"><span>Search agreements</span><span className="relative"><Search aria-hidden="true" className="absolute left-3 top-3 size-4 text-slate-400"/><Input value={query} onChange={e=>setQuery(e.target.value)} className="pl-9" placeholder="Title, purpose, or participant" /></span></label><label className="grid gap-1.5 text-sm font-medium">Status<select value={status} onChange={e=>setStatus(e.target.value)} className="min-h-10 rounded-md border bg-white px-3"><option value="all">All statuses</option>{Object.entries(STATUS_LABELS).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="grid gap-1.5 text-sm font-medium">Funding<select value={funding} onChange={e=>setFunding(e.target.value)} className="min-h-10 rounded-md border bg-white px-3"><option value="all">All funding modes</option><option value="none">No funding</option><option value="protection">Simulated protection</option><option value="conditional_intent">Conditional intent</option></select></label><Button type="button" variant="outline" onClick={reset}>Reset</Button></div><p className="text-sm text-slate-600" aria-live="polite">Showing {filtered.length} of {agreements.length} agreements.</p>{filtered.length ? <ul className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(item=><li key={item.id}><AgreementCard agreement={item}/></li>)}</ul> : <div className="rounded-xl border border-dashed bg-white p-10 text-center"><h2 className="text-xl font-semibold">No agreements match these filters</h2><p className="mx-auto mt-2 max-w-md text-slate-600">Reset the filters or create a draft to clarify a new shared commitment.</p><div className="mt-5 flex justify-center gap-3"><Button onClick={reset} variant="outline">Reset filters</Button><Button render={<Link href="/agreements/create"/>}>Create agreement</Button></div></div>}</div>; }
