"use client";
import { useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Info } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { createAgreementPreview } from "@/mocks/agreements";
import { validateAgreement, type FormErrors } from "@/lib/agreements/validation";
import type { CreateAgreementInput } from "@/types/agreement";

const initial: CreateAgreementInput = { title:"",purpose:"",participantName:"",participantResponsibility:"",obligation:"",successCondition:"",evidenceSource:"",deadline:"",fundingMode:"none",verificationMethod:"participant_confirmation",resolutionApproach:"",visibility:"participants" };
export function CreateAgreementForm() { const [input,setInput]=useState(initial); const [step,setStep]=useState(0); const [errors,setErrors]=useState<FormErrors>({}); const [preview,setPreview]=useState<string>(); const errorRef=useRef<HTMLDivElement>(null); const set=(key:keyof CreateAgreementInput,value:string)=>setInput(v=>({...v,[key]:value})); const validate=()=>{const next=validateAgreement(input);setErrors(next);if(Object.keys(next).length){setTimeout(()=>errorRef.current?.focus(),0);return false}return true}; const review=()=>{if(validate())setStep(1)}; const create=async()=>{const agreement=await createAgreementPreview(input);setPreview(agreement.id);setStep(2)}; return <div className="grid min-w-0 gap-6">
  <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-950"><p className="flex gap-2"><Info aria-hidden="true" className="mt-0.5 size-4 shrink-0"/><span><strong>Local demo only.</strong> This draft will not be saved or shared, and no funds will move.</span></p></div>
  <ol className="grid grid-cols-3 gap-2 text-xs sm:text-sm" aria-label="Creation progress">{["Draft terms","Review","Preview ready"].map((label,i)=><li key={label} aria-current={step===i?"step":undefined} className={`min-w-0 rounded-lg p-3 text-center ${step===i?"bg-teal-800 font-semibold text-white":"bg-slate-100 text-slate-600"}`}>{i+1}. {label}</li>)}</ol>
  {Object.keys(errors).length>0 && step===0 && <div ref={errorRef} tabIndex={-1} role="alert" className="rounded-xl border border-red-300 bg-red-50 p-4 focus:outline-2 focus:outline-red-700"><h2 className="font-semibold text-red-950">Please fix {Object.keys(errors).length} field{Object.keys(errors).length===1?"":"s"}</h2><ul className="mt-2 list-disc pl-5 text-sm text-red-900">{Object.entries(errors).map(([key,message])=><li key={key}><a className="underline" href={`#${key}`}>{message}</a></li>)}</ul></div>}
  {step===0 && <form onSubmit={e=>{e.preventDefault();review()}} noValidate className="grid gap-8"><Fieldset legend="Purpose and timing"><TextField id="title" label="Agreement title" value={input.title} error={errors.title} onChange={v=>set("title",v)} hint="Name the shared commitment, not a payment."/><Area id="purpose" label="Purpose" value={input.purpose} error={errors.purpose} onChange={v=>set("purpose",v)}/><TextField id="deadline" label="Deadline" type="date" value={input.deadline} error={errors.deadline} onChange={v=>set("deadline",v)}/></Fieldset><Fieldset legend="Participants and responsibilities"><TextField id="participantName" label="Other participant’s name" value={input.participantName} error={errors.participantName} onChange={v=>set("participantName",v)}/><Area id="participantResponsibility" label="Their responsibility" value={input.participantResponsibility} error={errors.participantResponsibility} onChange={v=>set("participantResponsibility",v)}/><Area id="obligation" label="Your obligation" value={input.obligation} error={errors.obligation} onChange={v=>set("obligation",v)}/></Fieldset><Fieldset legend="Success and evidence"><Area id="successCondition" label="Success condition" value={input.successCondition} error={errors.successCondition} onChange={v=>set("successCondition",v)}/><Area id="evidenceSource" label="Expected evidence and source" value={input.evidenceSource} error={errors.evidenceSource} onChange={v=>set("evidenceSource",v)}/><Select id="verificationMethod" label="Verification method" value={input.verificationMethod} onChange={v=>set("verificationMethod",v)} options={[['participant_confirmation','Participant confirmation'],['source_check','Source check'],['human_review','Human review']]}/></Fieldset><Fieldset legend="Optional protection and resolution"><Select id="fundingMode" label="Funding mode" value={input.fundingMode} onChange={v=>set("fundingMode",v)} options={[['none','No funding — non-financial agreement'],['protection','Simulated protection'],['conditional_intent','Conditional intent — not held or guaranteed']]}/><Area id="resolutionApproach" label="Resolution approach" value={input.resolutionApproach} error={errors.resolutionApproach} onChange={v=>set("resolutionApproach",v)} hint="Describe the non-financial outcome or how an authorized person reviews a simulated release/refund."/><Select id="visibility" label="Demo visibility" value={input.visibility} onChange={v=>set("visibility",v)} options={[['participants','Participants'],['private_link','Private link (mock choice; access control is not implemented)']]}/></Fieldset><div className="flex justify-end"><Button type="submit">Review draft <ArrowRight aria-hidden="true"/></Button></div></form>}
  {step===1 && <div className="grid gap-6"><div className="rounded-xl border bg-white p-6"><p className="text-xs font-semibold uppercase tracking-wide text-teal-800">Plain-language preview</p><h2 className="mt-2 text-2xl font-semibold">{input.title}</h2><p className="mt-3 text-slate-600">{input.purpose}</p><dl className="mt-6 grid gap-4 sm:grid-cols-2"><Review label="Participant" value={input.participantName}/><Review label="Deadline" value={`${input.deadline} (UTC)`}/><Review label="Success" value={input.successCondition}/><Review label="Evidence" value={input.evidenceSource}/><Review label="Funding" value={input.fundingMode==="none"?"No funding protection":input.fundingMode==="protection"?"Simulated protection only":"Conditional intent; funds are not held or guaranteed"}/><Review label="Resolution" value={input.resolutionApproach}/></dl><div className="mt-6 rounded-lg bg-amber-50 p-4 text-sm text-amber-950">This preview is not accepted terms. Consequential outcomes would require explicit authorization or human review.</div></div><div className="flex justify-between"><Button variant="outline" onClick={()=>setStep(0)}><ArrowLeft/>Edit</Button><Button onClick={create}>Create local preview</Button></div></div>}
  {step===2 && <div role="status" className="rounded-xl border bg-white p-8 text-center"><h2 className="text-2xl font-semibold">Local preview created</h2><p className="mx-auto mt-3 max-w-xl text-slate-600">The mock adapter constructed a deterministic draft in memory. It was not persisted, invited, funded, or authorized.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><Button disabled title="Invitations are not implemented in this demo">Send invitation (unavailable)</Button><Button variant="outline" onClick={()=>{setInput(initial);setErrors({});setPreview(undefined);setStep(0)}}>Create another</Button><Button render={<Link href="/agreements"/>}>Return to agreements</Button></div><p className="mt-4 text-xs text-slate-500">Preview reference: {preview}</p></div>}
  </div>; }
function Fieldset({legend,children}:{legend:string;children:React.ReactNode}){return <fieldset className="grid min-w-0 gap-5 rounded-xl border bg-white p-5"><legend className="px-2 text-lg font-semibold">{legend}</legend>{children}</fieldset>}
function TextField({id,label,value,onChange,error,hint,type="text"}:{id:string;label:string;value:string;onChange:(v:string)=>void;error?:string;hint?:string;type?:string}){return <label className="grid gap-1.5 font-medium" htmlFor={id}>{label}<Input id={id} type={type} value={value} onChange={e=>onChange(e.target.value)} aria-invalid={!!error} aria-describedby={`${id}-help ${id}-error`}/>{hint&&<span id={`${id}-help`} className="text-sm font-normal text-slate-500">{hint}</span>}{error&&<span id={`${id}-error`} className="text-sm font-normal text-red-700">{error}</span>}</label>}
function Area({id,label,value,onChange,error,hint}:{id:string;label:string;value:string;onChange:(v:string)=>void;error?:string;hint?:string}){return <label className="grid gap-1.5 font-medium" htmlFor={id}>{label}<textarea id={id} rows={3} value={value} onChange={e=>onChange(e.target.value)} aria-invalid={!!error} aria-describedby={`${id}-help ${id}-error`} className="rounded-md border bg-transparent px-3 py-2 text-sm focus-visible:outline-2 focus-visible:outline-teal-700"/>{hint&&<span id={`${id}-help`} className="text-sm font-normal text-slate-500">{hint}</span>}{error&&<span id={`${id}-error`} className="text-sm font-normal text-red-700">{error}</span>}</label>}
function Select({id,label,value,onChange,options}:{id:string;label:string;value:string;onChange:(v:string)=>void;options:string[][]}){return <label className="grid min-w-0 gap-1.5 font-medium" htmlFor={id}>{label}<select id={id} value={value} onChange={e=>onChange(e.target.value)} className="min-h-10 min-w-0 max-w-full rounded-md border bg-white px-3 text-sm">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Review({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 leading-6">{value}</dd></div>}
