import type { Assessment, EvidenceItem, EvidenceRevision, EvidenceSet, HumanReviewRequest, ReviewerDecision } from "./domain.ts";
import type { WorkflowAgreement, WorkflowMutation, WorkflowRepository, WorkflowResult } from "./service.ts";
const clone = <T>(value: T): T => structuredClone(value);
type StoredIdem = { fingerprint: string; type: string; id: string };
export class InMemoryWorkflowRepository implements WorkflowRepository {
  private agreements = new Map<string, WorkflowAgreement>(); private evidence = new Map<string, EvidenceItem>(); private revisions = new Map<string, EvidenceRevision>(); private sets = new Map<string, EvidenceSet>(); private assessments = new Map<string, Assessment>(); private reviews = new Map<string, HumanReviewRequest>(); private decisions = new Map<string, ReviewerDecision>(); private idem = new Map<string, StoredIdem>();
  seedAgreement(value: WorkflowAgreement) { this.agreements.set(`${value.document.agreementId}:${value.document.versionId}`, clone(value)); }
  private key(m: WorkflowMutation) { return `${m.actorId}:${m.operation}:${m.idempotencyKey}`; }
  private replay<T>(m: WorkflowMutation, type: string, source: Map<string, T>): WorkflowResult<T> | { kind: "idempotency_conflict" } | undefined { const prior = this.idem.get(this.key(m)); if (!prior) return; if (prior.fingerprint !== m.requestFingerprint || prior.type !== type) return { kind: "idempotency_conflict" }; const resource = source.get(prior.id); return resource ? { kind: "replayed", resource: clone(resource) } : { kind: "idempotency_conflict" }; }
  private remember(m: WorkflowMutation, type: string, id: string) { this.idem.set(this.key(m), { fingerprint: m.requestFingerprint, type, id }); }
  async agreement(a: string, v: string) { const value = this.agreements.get(`${a}:${v}`); return value ? clone(value) : null; }
  async submit(item: EvidenceItem, m: WorkflowMutation) { const replay = this.replay(m, "evidence", this.evidence); if (replay) return replay; this.evidence.set(item.evidenceId, clone(item)); this.revisions.set(item.currentRevisionId, clone(item.currentRevision)); this.remember(m, "evidence", item.evidenceId); return { kind: "created" as const, resource: clone(item) }; }
  async correct(id: string, expected: number, revision: EvidenceRevision, m: WorkflowMutation) { const replay = this.replay(m, "evidence", this.evidence); if (replay) return replay; const item = this.evidence.get(id); if (!item) return { kind: "not_found" as const }; if (item.revision !== expected || item.lifecycle !== "active") return { kind: "conflict" as const }; const updated = { ...item, currentRevisionId: revision.evidenceRevisionId, revision: item.revision + 1, currentRevision: clone(revision) }; this.revisions.set(revision.evidenceRevisionId, clone(revision)); this.evidence.set(id, updated); this.remember(m, "evidence", id); return { kind: "created" as const, resource: clone(updated) }; }
  async withdraw(id: string, expected: number, m: WorkflowMutation) { const replay = this.replay(m, "evidence", this.evidence); if (replay) return replay; const item = this.evidence.get(id); if (!item) return { kind: "not_found" as const }; if (item.revision !== expected || item.lifecycle !== "active") return { kind: "conflict" as const }; const updated = { ...item, lifecycle: "withdrawn" as const, revision: item.revision + 1 }; this.evidence.set(id, updated); this.remember(m, "evidence", id); return { kind: "created" as const, resource: clone(updated) }; }
  async getEvidence(a: string, id: string) { const v = this.evidence.get(id); return v?.agreementId === a ? clone(v) : null; } async listEvidence(a: string, v?: string) { return [...this.evidence.values()].filter((x) => x.agreementId === a && (!v || x.versionId === v)).sort((x,y) => y.createdAt.localeCompare(x.createdAt) || x.evidenceId.localeCompare(y.evidenceId)).map(clone); }
  async listEvidenceRevisions(id: string) { return [...this.revisions.values()].filter((revision) => revision.evidenceId === id).sort((a, b) => b.revisionNumber - a.revisionNumber).map(clone); }
  async saveAssessment(set: EvidenceSet, a: Assessment, m: WorkflowMutation) { const replay = this.replay(m, "assessment", this.assessments); if (replay) return replay; const duplicate = [...this.assessments.values()].find((item) => item.agreementId === a.agreementId && item.versionId === a.versionId && item.documentDigest === a.documentDigest && item.evidenceSetDigest === a.evidenceSetDigest && item.adapterVersion === a.adapterVersion && item.policyVersion === a.policyVersion && ["pending", "completed"].includes(item.status)); if (duplicate) { this.remember(m, "assessment", duplicate.assessmentId); return { kind: "replayed" as const, resource: clone(duplicate) }; } const same = [...this.sets.values()].find((x) => x.agreementId === set.agreementId && x.versionId === set.versionId && x.digest === set.digest); if (same) a = { ...a, evidenceSetId: same.evidenceSetId }; else this.sets.set(set.evidenceSetId, clone(set)); this.assessments.set(a.assessmentId, clone(a)); this.remember(m, "assessment", a.assessmentId); return { kind: "created" as const, resource: clone(a) }; }
  async getEvidenceSet(g: string, id: string) { const value = this.sets.get(id); return value?.agreementId === g ? clone(value) : null; }
  async getAssessment(g: string, id: string) { const v = this.assessments.get(id); return v?.agreementId === g ? clone(v) : null; } async listAssessments(g: string) { return [...this.assessments.values()].filter((x) => x.agreementId === g).sort((a,b) => b.occurredAt.localeCompare(a.occurredAt) || a.assessmentId.localeCompare(b.assessmentId)).map(clone); }
  async saveReview(r: HumanReviewRequest, m: WorkflowMutation) { const replay = this.replay(m, "review", this.reviews); if (replay) return replay; const duplicate = [...this.reviews.values()].find((x) => x.agreementId === r.agreementId && x.versionId === r.versionId && x.state !== "completed" && x.state !== "cancelled" && JSON.stringify(x.reasonCodes) === JSON.stringify(r.reasonCodes)); if (duplicate) return { kind: "replayed" as const, resource: clone(duplicate) }; this.reviews.set(r.reviewRequestId, clone(r)); this.remember(m, "review", r.reviewRequestId); return { kind: "created" as const, resource: clone(r) }; }
  async getReview(g: string, id: string) { const v = this.reviews.get(id); return v?.agreementId === g ? clone(v) : null; } async listReviews(g: string) { return [...this.reviews.values()].filter((x) => x.agreementId === g).sort((a,b) => b.createdAt.localeCompare(a.createdAt) || a.reviewRequestId.localeCompare(b.reviewRequestId)).map(clone); }
  async assignReview(id: string, accountId: string, expected: number) { const r = this.reviews.get(id); if (!r || r.revision !== expected || r.state !== "open") return null; const next = { ...r, assignedAccountId: accountId, state: "assigned" as const, revision: r.revision + 1, updatedAt: new Date().toISOString() }; this.reviews.set(id, next); return clone(next); }
  async decideReview(id: string, expected: number, d: ReviewerDecision, m: WorkflowMutation) { const replay = this.replay(m, "decision", this.decisions); if (replay) return replay; const r = this.reviews.get(id); if (!r) return { kind: "not_found" as const }; if (r.revision !== expected || (r.state !== "assigned" && r.state !== "in_review")) return { kind: "conflict" as const }; this.decisions.set(d.reviewerDecisionId, clone(d)); this.reviews.set(id, { ...r, state: "completed", revision: r.revision + 1, updatedAt: d.createdAt }); this.remember(m, "decision", d.reviewerDecisionId); return { kind: "created" as const, resource: clone(d) }; }
  async listReviewerDecisions(agreementId: string) { return [...this.decisions.values()].filter((decision) => decision.agreementId === agreementId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(clone); }
  getEvidenceSetForTest(id: string) { const value = this.sets.get(id); return value ? clone(value) : undefined; } getDecisionsForTest() { return [...this.decisions.values()].map(clone); }
}
