import { createHash } from "node:crypto";
import type { AgreementLanguageDocument } from "../../lib/agreement-language/types.ts";
import type { RequestContext, AgreementMembership } from "../agreements/application/contracts.ts";
import type { AssessmentAdapter } from "./adapter.ts";
import { acceptedVersion, evidenceSetDigest, requirementState, type Assessment, type AssessmentCapability, type EvidenceItem, type EvidenceRevision, type EvidenceSet, type HumanReviewRequest, type ReviewerDecision, type ReviewReason } from "./domain.ts";
import { EvidenceError, resolvePolicy, validateMetadata, validateSource } from "./validation.ts";

export interface WorkflowAgreement { document: AgreementLanguageDocument; acceptedPartyIds: string[]; memberships: AgreementMembership[] }
export interface WorkflowMutation { actorId: string; operation: string; idempotencyKey: string; requestFingerprint: string; correlationId: string; occurredAt: string }
export type WorkflowResult<T> = { kind: "created" | "replayed"; resource: T };
export interface WorkflowRepository {
  agreement(agreementId: string, versionId: string): Promise<WorkflowAgreement | null>;
  submit(item: EvidenceItem, mutation: WorkflowMutation): Promise<WorkflowResult<EvidenceItem> | { kind: "idempotency_conflict" }>;
  correct(itemId: string, expectedRevision: number, revision: EvidenceRevision, mutation: WorkflowMutation): Promise<WorkflowResult<EvidenceItem> | { kind: "idempotency_conflict" | "not_found" | "conflict" }>;
  withdraw(itemId: string, expectedRevision: number, mutation: WorkflowMutation): Promise<WorkflowResult<EvidenceItem> | { kind: "idempotency_conflict" | "not_found" | "conflict" }>;
  getEvidence(agreementId: string, evidenceId: string): Promise<EvidenceItem | null>; listEvidence(agreementId: string, versionId?: string): Promise<EvidenceItem[]>;
  listEvidenceRevisions(evidenceId: string): Promise<EvidenceRevision[]>;
  saveAssessment(set: EvidenceSet, assessment: Assessment, mutation: WorkflowMutation): Promise<WorkflowResult<Assessment> | { kind: "idempotency_conflict" }>;
  getEvidenceSet(agreementId: string, id: string): Promise<EvidenceSet | null>;
  getAssessment(agreementId: string, id: string): Promise<Assessment | null>; listAssessments(agreementId: string): Promise<Assessment[]>;
  saveReview(request: HumanReviewRequest, mutation: WorkflowMutation): Promise<WorkflowResult<HumanReviewRequest> | { kind: "idempotency_conflict" }>;
  getReview(agreementId: string, id: string): Promise<HumanReviewRequest | null>; listReviews(agreementId: string): Promise<HumanReviewRequest[]>;
  assignReview(id: string, accountId: string, expectedRevision: number): Promise<HumanReviewRequest | null>;
  decideReview(id: string, expectedRevision: number, decision: ReviewerDecision, mutation: WorkflowMutation): Promise<WorkflowResult<ReviewerDecision> | { kind: "idempotency_conflict" | "conflict" | "not_found" }>;
  listReviewerDecisions(agreementId: string): Promise<ReviewerDecision[]>;
}

export interface SubmitEvidenceInput { agreementId: string; versionId: string; evidenceRequirementId: string; criterionIds: string[]; sourceConstraintId: string; sourceRefKind?: EvidenceRevision["sourceRefKind"]; sourceRef?: string; sourceDisplayLabel?: string; observedAt?: string; capturedAt: string; evidenceClass: EvidenceRevision["evidenceClass"]; origin: EvidenceRevision["origin"]; availability?: EvidenceRevision["availability"]; integrity?: EvidenceRevision["integrity"]; metadata: unknown; contentDigest?: string }
export interface ControlledObservationInput { agreementId: string; versionId: string; evidenceRequirementId: string; criterionIds: string[]; sourceConstraintId: string; fixtureId: string; displayLabel: string; observedAt?: string; capturedAt: string; metadata: unknown; contentDigest: string }
type Ids = (kind: "evidence" | "evidence-revision" | "evidence-set" | "assessment" | "review" | "decision") => string;

export class EvidenceAssessmentService {
  private readonly repository: WorkflowRepository; private readonly now: () => Date; private readonly ids: Ids;
  constructor(repository: WorkflowRepository, now: () => Date, ids: Ids) { this.repository = repository; this.now = now; this.ids = ids; }
  private account(context: RequestContext) { if (context.principal.kind !== "account") throw new EvidenceError("AUTHENTICATION_REQUIRED", "Sign in to continue.", 401); if (context.principal.accountState !== "active") throw new EvidenceError("PERMISSION_DENIED", "The resource was not found.", 404); return context.principal.accountId; }
  private async scope(context: RequestContext, agreementId: string, versionId: string) { const accountId = this.account(context); const scope = await this.repository.agreement(agreementId, versionId); if (!scope || !acceptedVersion(scope.document, scope.acceptedPartyIds)) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); const membership = scope.memberships.find((m) => m.accountId === accountId && m.state === "active"); if (!membership) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); return { accountId, membership, ...scope }; }
  private visible(scope: Awaited<ReturnType<EvidenceAssessmentService["scope"]>>, requirementId: string) { const requirement = scope.document.evidencePolicy.evidenceRequirements.find((item) => item.evidenceRequirementId === requirementId); if (!requirement) return false; if (requirement.sensitivity !== "standard") return false; if (requirement.visibility === "participants") return true; if (requirement.visibility === "authorized_reviewers") return scope.membership.role === "reviewer"; return false; }
  async authorizedRequirements(context: RequestContext, agreementId: string, versionId: string) { const scope = await this.scope(context, agreementId, versionId); return scope.document.evidencePolicy.evidenceRequirements.filter((item) => this.visible(scope, item.evidenceRequirementId)); }
  private mutation(context: RequestContext, operation: string, key: string, fingerprint: string): WorkflowMutation { return { actorId: this.account(context), operation, idempotencyKey: key, requestFingerprint: fingerprint, correlationId: context.correlationId, occurredAt: this.now().toISOString() }; }
  private outcome<T>(result: WorkflowResult<T> | { kind: string }): WorkflowResult<T> { if (result.kind === "idempotency_conflict") throw new EvidenceError("IDEMPOTENCY_KEY_REUSED", "The idempotency key was already used for a different request.", 409); if (result.kind === "conflict") throw new EvidenceError("EVIDENCE_VERSION_CONFLICT", "The resource changed before this request completed.", 409); if (result.kind === "not_found") throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); return result as WorkflowResult<T>; }

  async submitEvidence(context: RequestContext, input: SubmitEvidenceInput, idempotencyKey: string, fingerprint: string) {
    const scope = await this.scope(context, input.agreementId, input.versionId); const { requirement, source } = resolvePolicy(input.evidenceRequirementId, input.sourceConstraintId, scope.document);
    if (!requirement.submitterPartyIds.includes(scope.membership.partyId)) throw new EvidenceError("EVIDENCE_NOT_ALLOWED", "Evidence submission is not allowed.", 404);
    if (input.evidenceClass !== requirement.evidenceClass || input.criterionIds.length === 0 || input.criterionIds.some((id) => !requirement.criterionIds.includes(id))) throw new EvidenceError("EVIDENCE_INVALID", "Evidence does not match the accepted requirement.");
    validateSource(input.sourceRefKind, input.sourceRef); const metadata = validateMetadata(input.metadata, source); const receivedAt = this.now().toISOString(); const evidenceId = this.ids("evidence"); const revisionId = this.ids("evidence-revision");
    const revision: EvidenceRevision = { ...input, evidenceRevisionId: revisionId, evidenceId, agreementId: input.agreementId, versionId: input.versionId, revisionNumber: 1, criterionIds: [...new Set(input.criterionIds)].sort(), submittedByPartyId: scope.membership.partyId, submittedByAccountId: scope.accountId, capturedAt: new Date(input.capturedAt).toISOString(), receivedAt, availability: input.availability ?? "available", integrity: input.integrity ?? "unverified", validation: "valid", validationReasons: [], metadata };
    const item: EvidenceItem = { evidenceId, agreementId: input.agreementId, versionId: input.versionId, evidenceRequirementId: input.evidenceRequirementId, currentRevisionId: revisionId, lifecycle: "active", createdAt: receivedAt, createdByAccountId: scope.accountId, revision: 1, currentRevision: revision };
    return this.outcome(await this.repository.submit(item, this.mutation(context, "submit_evidence", idempotencyKey, fingerprint)));
  }

  async submitControlledObservation(context: RequestContext, input: ControlledObservationInput, idempotencyKey: string, fingerprint: string) {
    const scope = await this.scope(context, input.agreementId, input.versionId); const { requirement } = resolvePolicy(input.evidenceRequirementId, input.sourceConstraintId, scope.document);
    if (!this.visible(scope, input.evidenceRequirementId)) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404);
    return this.submitEvidence(context, { ...input, evidenceClass: requirement.evidenceClass, origin: "external", sourceRefKind: "fixture", sourceRef: input.fixtureId, sourceDisplayLabel: input.displayLabel, availability: "available", integrity: "unverified" }, idempotencyKey, fingerprint);
  }

  async correctEvidence(context: RequestContext, agreementId: string, evidenceId: string, expectedRevision: number, changes: Omit<SubmitEvidenceInput, "agreementId" | "versionId" | "evidenceRequirementId">, key: string, fingerprint: string) {
    const current = await this.repository.getEvidence(agreementId, evidenceId); if (!current) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); const scope = await this.scope(context, agreementId, current.versionId); if (current.createdByAccountId !== scope.accountId) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404);
    const { requirement, source } = resolvePolicy(current.evidenceRequirementId, changes.sourceConstraintId, scope.document); if (changes.evidenceClass !== requirement.evidenceClass || changes.criterionIds.some((id) => !requirement.criterionIds.includes(id))) throw new EvidenceError("EVIDENCE_INVALID", "Evidence does not match the accepted requirement."); validateSource(changes.sourceRefKind, changes.sourceRef); const metadata = validateMetadata(changes.metadata, source);
    const revision: EvidenceRevision = { ...changes, evidenceRevisionId: this.ids("evidence-revision"), evidenceId, agreementId, versionId: current.versionId, revisionNumber: current.currentRevision.revisionNumber + 1, supersedesRevisionId: current.currentRevisionId, submittedByPartyId: scope.membership.partyId, submittedByAccountId: scope.accountId, criterionIds: [...new Set(changes.criterionIds)].sort(), capturedAt: new Date(changes.capturedAt).toISOString(), receivedAt: this.now().toISOString(), availability: changes.availability ?? "available", integrity: changes.integrity ?? "unverified", validation: "valid", validationReasons: [], metadata };
    return this.outcome(await this.repository.correct(evidenceId, expectedRevision, revision, this.mutation(context, "correct_evidence", key, fingerprint)));
  }
  async withdrawEvidence(context: RequestContext, agreementId: string, evidenceId: string, expectedRevision: number, key: string, fingerprint: string) { const current = await this.repository.getEvidence(agreementId, evidenceId); if (!current) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); const scope = await this.scope(context, agreementId, current.versionId); if (current.createdByAccountId !== scope.accountId) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); return this.outcome(await this.repository.withdraw(evidenceId, expectedRevision, this.mutation(context, "withdraw_evidence", key, fingerprint))); }
  async listEvidence(context: RequestContext, agreementId: string, versionId: string) { const scope = await this.scope(context, agreementId, versionId); return (await this.repository.listEvidence(agreementId, versionId)).filter((item) => this.visible(scope, item.evidenceRequirementId)); }
  async getEvidence(context: RequestContext, agreementId: string, evidenceId: string) { const item = await this.repository.getEvidence(agreementId, evidenceId); if (!item) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); const scope = await this.scope(context, agreementId, item.versionId); if (!this.visible(scope, item.evidenceRequirementId)) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); return { ...item, revisions: await this.repository.listEvidenceRevisions(evidenceId) }; }
  async workflowContext(context: RequestContext, agreementId: string, versionId: string) { const scope = await this.scope(context, agreementId, versionId); const items = await this.repository.listEvidence(agreementId, versionId); const requirementStates = scope.document.evidencePolicy.evidenceRequirements.map((requirement) => ({ evidenceRequirementId: requirement.evidenceRequirementId, ...requirementState(items.filter((item) => item.evidenceRequirementId === requirement.evidenceRequirementId && item.lifecycle === "active").map((item) => item.currentRevision), requirement.minimumDistinctSources, requirement.independentSourcesRequired) })); return { agreementId, versionId, acceptedAgreementVersion: scope.document.agreementVersion, versionState: scope.document.versionState, partyId: scope.membership.partyId, role: scope.membership.role, canSubmitEvidence: scope.document.evidencePolicy.evidenceRequirements.some((requirement) => requirement.submitterPartyIds.includes(scope.membership.partyId)), canAssignReview: scope.membership.role === "reviewer", canRecordReviewerDecision: scope.membership.role === "reviewer", requirementStates }; }

  async getAssessmentCapability(context: RequestContext, agreementId: string, versionId: string): Promise<AssessmentCapability> {
    const scope = await this.scope(context, agreementId, versionId); const documentDigest = createHash("sha256").update(JSON.stringify(scope.document)).digest("hex"); const items = (await this.repository.listEvidence(agreementId, versionId)).filter((item) => item.lifecycle === "active"); const requirements = scope.document.evidencePolicy.evidenceRequirements;
    const reasons: string[] = []; if (context.source === "api" && !(process.env.NODE_ENV === "development" && process.env.HMM_AI_ASSESSMENT_UI_ENABLED === "true")) reasons.push("FEATURE_DISABLED"); if (scope.document.versionState !== "accepted") reasons.push("VERSION_NOT_CURRENT_ACCEPTED"); if (!scope.document.verificationPolicy.criterionIds.length || !scope.document.verificationPolicy.reviewRoute) reasons.push("VERIFICATION_POLICY_UNAVAILABLE"); if (!(["owner", "participant"] as string[]).includes(scope.membership.role)) reasons.push("ROLE_NOT_ELIGIBLE"); if (requirements.some((item) => !this.visible(scope, item.evidenceRequirementId))) reasons.push("PRIVATE_EVIDENCE_UNSUPPORTED");
    const revisions = items.map((item) => item.currentRevision); for (const requirement of requirements) { const state = requirementState(items.filter((item) => item.evidenceRequirementId === requirement.evidenceRequirementId).map((item) => item.currentRevision), requirement.minimumDistinctSources, requirement.independentSourcesRequired).state; if (state !== "satisfied_for_assessment") reasons.push(`EVIDENCE_${state.toUpperCase()}`); }
    const canonical = evidenceSetDigest(agreementId, versionId, revisions.map((item) => item.evidenceRevisionId)); const unavailable = reasons.some((reason) => ["FEATURE_DISABLED", "VERSION_NOT_CURRENT_ACCEPTED", "VERIFICATION_POLICY_UNAVAILABLE", "ROLE_NOT_ELIGIBLE", "PRIVATE_EVIDENCE_UNSUPPORTED"].includes(reason)); const matching = (await this.repository.listAssessments(agreementId)).find((item) => item.versionId === versionId && item.documentDigest === documentDigest && item.evidenceSetDigest === canonical.digest);
    return { status: unavailable ? "unavailable" : reasons.length ? "eligible_with_gaps" : "eligible", reasonCodes: [...new Set(reasons)].sort(), canRequest: !unavailable, providerClass: "local_deterministic", providerLabel: "Local deterministic assessment", budgetState: "available", agreementId, versionId, acceptedAgreementVersion: scope.document.agreementVersion, documentDigest, evidenceSetDigest: canonical.digest, evidenceCanonicalizationVersion: "evidence-set-v1", evidenceRevisionCount: revisions.length, ...(matching ? { activeAssessmentId: matching.assessmentId } : {}) };
  }

  async requestAssessment(context: RequestContext, agreementId: string, versionId: string, adapter: AssessmentAdapter, key: string, fingerprint: string) {
    const scope = await this.scope(context, agreementId, versionId); if (context.source === "api" && !(process.env.NODE_ENV === "development" && process.env.HMM_AI_ASSESSMENT_UI_ENABLED === "true")) throw new EvidenceError("PROVIDER_DISABLED", "Advisory assessment requests are unavailable.", 503); if (scope.document.versionState !== "accepted") throw new EvidenceError("ASSESSMENT_CONTEXT_STALE", "The accepted agreement version changed. Refresh before requesting an assessment.", 409); if (!(["owner", "participant"] as string[]).includes(scope.membership.role) && context.source !== "test") throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); if (scope.document.evidencePolicy.evidenceRequirements.some((item) => !this.visible(scope, item.evidenceRequirementId))) throw new EvidenceError("PRIVACY_POLICY_UNENFORCEABLE", "The assessment is unavailable because its privacy scope cannot be enforced.", 422); const items = (await this.repository.listEvidence(agreementId, versionId)).filter((i) => i.lifecycle === "active"); const revisions = items.map((i) => i.currentRevision); const states = new Map(scope.document.evidencePolicy.evidenceRequirements.map((r) => [r.evidenceRequirementId, requirementState(revisions.filter((e) => items.find((i) => i.evidenceId === e.evidenceId)?.evidenceRequirementId === r.evidenceRequirementId), r.minimumDistinctSources, r.independentSourcesRequired).state]));
    const canonical = evidenceSetDigest(agreementId, versionId, revisions.map((r) => r.evidenceRevisionId)); const createdAt = this.now().toISOString(); const set: EvidenceSet = { evidenceSetId: this.ids("evidence-set"), agreementId, versionId, canonicalizationVersion: "evidence-set-v1", digest: canonical.digest, evidenceRevisionIds: canonical.ordered, createdAt, createdByAccountId: scope.accountId };
    const documentDigest = createHash("sha256").update(JSON.stringify(scope.document)).digest("hex"); const draft = await adapter.evaluate({ document: scope.document, documentDigest, evidenceSetId: set.evidenceSetId, evidenceSetDigest: set.digest, evidenceCanonicalizationVersion: set.canonicalizationVersion, evidence: revisions, requirementStates: states }); const current = (await this.repository.listEvidence(agreementId, versionId)).filter((item) => item.lifecycle === "active"); if (evidenceSetDigest(agreementId, versionId, current.map((item) => item.currentRevisionId)).digest !== set.digest) throw new EvidenceError("ASSESSMENT_CONTEXT_STALE", "The evidence changed while the assessment was running. No result was recorded.", 409); const allowedCriteria = new Set(scope.document.verificationPolicy.criterionIds); const allowedRevisions = new Set(canonical.ordered); if (draft.findings.length > 100 || draft.findings.some((finding) => !allowedCriteria.has(finding.criterionId) || finding.explanation.length > 2_000 || [...finding.supportingEvidenceRevisionIds, ...finding.conflictingEvidenceRevisionIds].some((id) => !allowedRevisions.has(id)))) throw new EvidenceError("MALFORMED_OUTPUT", "The assessment could not be validated.", 422); const assessment: Assessment = { assessmentId: this.ids("assessment"), agreementId, versionId, documentDigest, evidenceSetId: set.evidenceSetId, evidenceSetDigest: set.digest, evidenceCanonicalizationVersion: set.canonicalizationVersion, adapterKind: adapter.kind, adapterVersion: adapter.version, providerClass: "local_deterministic", providerName: "Human Made Money deterministic evaluator", modelVersion: "none", promptVersion: "structured-deterministic-v1", schemaVersion: "assessment-draft-v2", claimReferenceContractVersion: "claim-reference-v1", actionContractVersion: "advisory-action-v1", policyVersion: scope.document.verificationPolicy.policyVersion, status: "completed", criterionFindings: draft.findings, confidence: draft.confidence, limitations: draft.limitations, recommendedNextAction: draft.recommendedNextAction, authoritySafe: true, semanticExpectationMatched: "not_applicable", acceptableActionMatched: "not_applicable", requestedByAccountId: scope.accountId, requestedByPartyId: scope.membership.partyId, requestedByRole: scope.membership.role, requestedAt: createdAt, completedAt: this.now().toISOString(), occurredAt: createdAt, revision: 1 };
    return this.outcome(await this.repository.saveAssessment(set, assessment, this.mutation(context, "request_assessment", key, fingerprint)));
  }
  async requestControlledAssessment(context: RequestContext, agreementId: string, versionId: string, adapter: AssessmentAdapter, key: string, fingerprint: string) { const scope = await this.scope(context, agreementId, versionId); if (scope.document.evidencePolicy.evidenceRequirements.some((item) => !this.visible(scope, item.evidenceRequirementId))) throw new EvidenceError("PRIVACY_POLICY_UNENFORCEABLE", "The assessment is unavailable because its privacy scope cannot be enforced.", 404); return this.requestAssessment(context, agreementId, versionId, adapter, key, fingerprint); }
  async listAssessments(context: RequestContext, agreementId: string, versionId: string) { await this.scope(context, agreementId, versionId); return (await this.repository.listAssessments(agreementId)).filter((item) => item.versionId === versionId); }
  async getAssessment(context: RequestContext, agreementId: string, id: string) { const value = await this.repository.getAssessment(agreementId, id); if (!value) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); const scope = await this.scope(context, agreementId, value.versionId); const set = await this.repository.getEvidenceSet(agreementId, value.evidenceSetId); const items = await this.repository.listEvidence(agreementId, value.versionId); if (!set || items.some((item) => set.evidenceRevisionIds.includes(item.currentRevisionId) && !this.visible(scope, item.evidenceRequirementId))) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); return value; }

  async requestHumanReview(context: RequestContext, agreementId: string, versionId: string, input: { assessmentId?: string; evidenceSetId?: string; reasonCodes: ReviewReason[]; affectedCriterionIds: string[] }, key: string, fingerprint: string) { const scope = await this.scope(context, agreementId, versionId); const allowedReasons = new Set<ReviewReason>(["missing_required_evidence", "conflicting_evidence", "source_unavailable", "manual_assessment", "low_or_unassessed_confidence", "participant_challenge", "dispute_or_risk_flag", "evaluator_failure", "consequential_outcome", "version_or_authority_unproven"]); if (!input.reasonCodes.length || input.reasonCodes.some((reason) => !allowedReasons.has(reason)) || !input.affectedCriterionIds.length || input.affectedCriterionIds.some((id) => !scope.document.verificationPolicy.criterionIds.includes(id))) throw new EvidenceError("EVIDENCE_INVALID", "The review request does not match the accepted policy."); const assessment = input.assessmentId ? await this.repository.getAssessment(agreementId, input.assessmentId) : null; const set = input.evidenceSetId ? await this.repository.getEvidenceSet(agreementId, input.evidenceSetId) : null; if ((input.assessmentId && (!assessment || assessment.versionId !== versionId)) || (input.evidenceSetId && (!set || set.versionId !== versionId)) || (assessment && set && assessment.evidenceSetId !== set.evidenceSetId)) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); const createdAt = this.now().toISOString(); const request: HumanReviewRequest = { reviewRequestId: this.ids("review"), agreementId, versionId, ...input, reasonCodes: [...new Set(input.reasonCodes)].sort(), affectedCriterionIds: [...new Set(input.affectedCriterionIds)].sort(), requestedByAccountId: scope.accountId, route: scope.document.verificationPolicy.reviewRoute, state: "open", createdAt, updatedAt: createdAt, revision: 1 }; return this.outcome(await this.repository.saveReview(request, this.mutation(context, "request_human_review", key, fingerprint))); }
  async assignReview(context: RequestContext, agreementId: string, id: string, expectedRevision: number) { const request = await this.repository.getReview(agreementId, id); if (!request) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); const scope = await this.scope(context, agreementId, request.versionId); if (scope.membership.role !== "reviewer") throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); const result = await this.repository.assignReview(id, scope.accountId, expectedRevision); if (!result) throw new EvidenceError("REVIEW_CONFLICT", "The review request changed before this request completed.", 409); return result; }
  async recordReviewerDecision(context: RequestContext, agreementId: string, id: string, expectedRevision: number, input: Omit<ReviewerDecision, "reviewerDecisionId" | "reviewRequestId" | "agreementId" | "versionId" | "reviewerAccountId" | "reviewerPartyId" | "authorityBasis" | "createdAt">, key: string, fingerprint: string) { const request = await this.repository.getReview(agreementId, id); if (!request) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); const scope = await this.scope(context, agreementId, request.versionId); if (scope.membership.role !== "reviewer" || request.assignedAccountId !== scope.accountId || request.route !== scope.document.verificationPolicy.reviewRoute) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); const items = await this.repository.listEvidence(agreementId, request.versionId); if (items.some((item) => input.evidenceRevisionIds.includes(item.currentRevisionId) && (item.currentRevision.submittedByAccountId === scope.accountId || item.currentRevision.submittedByPartyId === scope.membership.partyId))) throw new EvidenceError("EVIDENCE_NOT_ALLOWED", "A reviewer cannot decide a challenge to their own evidence.", 403); const decision: ReviewerDecision = { ...input, reviewerDecisionId: this.ids("decision"), reviewRequestId: id, agreementId, versionId: request.versionId, reviewerAccountId: scope.accountId, reviewerPartyId: scope.membership.partyId, authorityBasis: "active_assigned_reviewer_membership", createdAt: this.now().toISOString() }; return this.outcome(await this.repository.decideReview(id, expectedRevision, decision, this.mutation(context, "record_reviewer_decision", key, fingerprint))); }
  async listReviews(context: RequestContext, agreementId: string, versionId: string) { await this.scope(context, agreementId, versionId); return this.repository.listReviews(agreementId); }
  async listReviewerDecisions(context: RequestContext, agreementId: string, versionId: string) { await this.scope(context, agreementId, versionId); return this.repository.listReviewerDecisions(agreementId); }
}
