import type { AgreementLanguageDocument } from "../../lib/agreement-language/types.ts";
import type { RequestContext, AgreementMembership } from "../agreements/application/contracts.ts";
import type { AssessmentAdapter } from "./adapter.ts";
import { acceptedVersion, evidenceSetDigest, requirementState, type Assessment, type EvidenceItem, type EvidenceRevision, type EvidenceSet, type HumanReviewRequest, type ReviewerDecision, type ReviewReason } from "./domain.ts";
import { EvidenceError, resolvePolicy, validateMetadata, validateSource } from "./validation.ts";

export interface WorkflowAgreement { document: AgreementLanguageDocument; acceptedPartyIds: string[]; memberships: AgreementMembership[] }
export interface WorkflowMutation { actorId: string; operation: string; idempotencyKey: string; requestFingerprint: string; correlationId: string; occurredAt: string }
export type WorkflowResult<T> = { kind: "created" | "replayed"; resource: T };
export interface WorkflowRepository {
  agreement(agreementId: string, versionId: string): Promise<WorkflowAgreement | null>;
  submit(item: EvidenceItem, mutation: WorkflowMutation): Promise<WorkflowResult<EvidenceItem> | { kind: "idempotency_conflict" }>;
  correct(itemId: string, expectedRevision: number, revision: EvidenceRevision, mutation: WorkflowMutation): Promise<WorkflowResult<EvidenceItem> | { kind: "idempotency_conflict" | "not_found" | "conflict" }>;
  withdraw(itemId: string, expectedRevision: number, mutation: WorkflowMutation): Promise<WorkflowResult<EvidenceItem> | { kind: "idempotency_conflict" | "not_found" | "conflict" }>;
  getEvidence(agreementId: string, evidenceId: string): Promise<EvidenceItem | null>; listEvidence(agreementId: string, versionId?: string): Promise<EvidenceItem[]>;
  listEvidenceRevisions(evidenceId: string): Promise<EvidenceRevision[]>;
  saveAssessment(set: EvidenceSet, assessment: Assessment, mutation: WorkflowMutation): Promise<WorkflowResult<Assessment> | { kind: "idempotency_conflict" }>;
  getAssessment(agreementId: string, id: string): Promise<Assessment | null>; listAssessments(agreementId: string): Promise<Assessment[]>;
  saveReview(request: HumanReviewRequest, mutation: WorkflowMutation): Promise<WorkflowResult<HumanReviewRequest> | { kind: "idempotency_conflict" }>;
  getReview(agreementId: string, id: string): Promise<HumanReviewRequest | null>; listReviews(agreementId: string): Promise<HumanReviewRequest[]>;
  assignReview(id: string, accountId: string, expectedRevision: number): Promise<HumanReviewRequest | null>;
  decideReview(id: string, expectedRevision: number, decision: ReviewerDecision, mutation: WorkflowMutation): Promise<WorkflowResult<ReviewerDecision> | { kind: "idempotency_conflict" | "conflict" | "not_found" }>;
  listReviewerDecisions(agreementId: string): Promise<ReviewerDecision[]>;
}

export interface SubmitEvidenceInput { agreementId: string; versionId: string; evidenceRequirementId: string; criterionIds: string[]; sourceConstraintId: string; sourceRefKind?: EvidenceRevision["sourceRefKind"]; sourceRef?: string; sourceDisplayLabel?: string; observedAt?: string; capturedAt: string; evidenceClass: EvidenceRevision["evidenceClass"]; origin: EvidenceRevision["origin"]; availability?: EvidenceRevision["availability"]; integrity?: EvidenceRevision["integrity"]; metadata: unknown; contentDigest?: string }
type Ids = (kind: "evidence" | "evidence-revision" | "evidence-set" | "assessment" | "review" | "decision") => string;

export class EvidenceAssessmentService {
  private readonly repository: WorkflowRepository; private readonly now: () => Date; private readonly ids: Ids;
  constructor(repository: WorkflowRepository, now: () => Date, ids: Ids) { this.repository = repository; this.now = now; this.ids = ids; }
  private account(context: RequestContext) { if (context.principal.kind !== "account") throw new EvidenceError("AUTHENTICATION_REQUIRED", "Sign in to continue.", 401); if (context.principal.accountState !== "active") throw new EvidenceError("PERMISSION_DENIED", "The resource was not found.", 404); return context.principal.accountId; }
  private async scope(context: RequestContext, agreementId: string, versionId: string) { const accountId = this.account(context); const scope = await this.repository.agreement(agreementId, versionId); if (!scope || !acceptedVersion(scope.document, scope.acceptedPartyIds)) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); const membership = scope.memberships.find((m) => m.accountId === accountId && m.state === "active"); if (!membership) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); return { accountId, membership, ...scope }; }
  private mutation(context: RequestContext, operation: string, key: string, fingerprint: string): WorkflowMutation { return { actorId: this.account(context), operation, idempotencyKey: key, requestFingerprint: fingerprint, correlationId: context.correlationId, occurredAt: this.now().toISOString() }; }
  private outcome<T>(result: WorkflowResult<T> | { kind: string }): WorkflowResult<T> { if (result.kind === "idempotency_conflict") throw new EvidenceError("IDEMPOTENCY_KEY_REUSED", "The idempotency key was already used for a different request.", 409); if (result.kind === "conflict") throw new EvidenceError("EVIDENCE_VERSION_CONFLICT", "The resource changed before this request completed.", 409); if (result.kind === "not_found") throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); return result as WorkflowResult<T>; }

  async submitEvidence(context: RequestContext, input: SubmitEvidenceInput, idempotencyKey: string, fingerprint: string) {
    const scope = await this.scope(context, input.agreementId, input.versionId); const { requirement, source } = resolvePolicy(input.evidenceRequirementId, input.sourceConstraintId, scope.document);
    if (!requirement.submitterPartyIds.includes(scope.membership.partyId)) throw new EvidenceError("EVIDENCE_NOT_ALLOWED", "Evidence submission is not allowed.", 404);
    if (input.evidenceClass !== requirement.evidenceClass || input.criterionIds.length === 0 || input.criterionIds.some((id) => !requirement.criterionIds.includes(id))) throw new EvidenceError("EVIDENCE_INVALID", "Evidence does not match the accepted requirement.");
    validateSource(input.sourceRefKind, input.sourceRef); const metadata = validateMetadata(input.metadata, source); const receivedAt = this.now().toISOString(); const evidenceId = this.ids("evidence"); const revisionId = this.ids("evidence-revision");
    const revision: EvidenceRevision = { ...input, evidenceRevisionId: revisionId, evidenceId, agreementId: input.agreementId, versionId: input.versionId, revisionNumber: 1, criterionIds: [...new Set(input.criterionIds)].sort(), submittedByPartyId: scope.membership.partyId, submittedByAccountId: scope.accountId, capturedAt: new Date(input.capturedAt).toISOString(), receivedAt, availability: input.availability ?? "available", integrity: input.integrity ?? "unverified", validation: "valid", validationReasons: [], metadata };
    const item: EvidenceItem = { evidenceId, agreementId: input.agreementId, versionId: input.versionId, evidenceRequirementId: input.evidenceRequirementId, currentRevisionId: revisionId, lifecycle: "active", createdAt: receivedAt, createdByAccountId: scope.accountId, revision: 1, currentRevision: revision };
    return this.outcome(await this.repository.submit(item, this.mutation(context, "submit_evidence", idempotencyKey, fingerprint)));
  }

  async correctEvidence(context: RequestContext, agreementId: string, evidenceId: string, expectedRevision: number, changes: Omit<SubmitEvidenceInput, "agreementId" | "versionId" | "evidenceRequirementId">, key: string, fingerprint: string) {
    const current = await this.repository.getEvidence(agreementId, evidenceId); if (!current) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); const scope = await this.scope(context, agreementId, current.versionId); if (current.createdByAccountId !== scope.accountId) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404);
    const { requirement, source } = resolvePolicy(current.evidenceRequirementId, changes.sourceConstraintId, scope.document); if (changes.evidenceClass !== requirement.evidenceClass || changes.criterionIds.some((id) => !requirement.criterionIds.includes(id))) throw new EvidenceError("EVIDENCE_INVALID", "Evidence does not match the accepted requirement."); validateSource(changes.sourceRefKind, changes.sourceRef); const metadata = validateMetadata(changes.metadata, source);
    const revision: EvidenceRevision = { ...changes, evidenceRevisionId: this.ids("evidence-revision"), evidenceId, agreementId, versionId: current.versionId, revisionNumber: current.currentRevision.revisionNumber + 1, supersedesRevisionId: current.currentRevisionId, submittedByPartyId: scope.membership.partyId, submittedByAccountId: scope.accountId, criterionIds: [...new Set(changes.criterionIds)].sort(), capturedAt: new Date(changes.capturedAt).toISOString(), receivedAt: this.now().toISOString(), availability: changes.availability ?? "available", integrity: changes.integrity ?? "unverified", validation: "valid", validationReasons: [], metadata };
    return this.outcome(await this.repository.correct(evidenceId, expectedRevision, revision, this.mutation(context, "correct_evidence", key, fingerprint)));
  }
  async withdrawEvidence(context: RequestContext, agreementId: string, evidenceId: string, expectedRevision: number, key: string, fingerprint: string) { const current = await this.repository.getEvidence(agreementId, evidenceId); if (!current) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); const scope = await this.scope(context, agreementId, current.versionId); if (current.createdByAccountId !== scope.accountId) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); return this.outcome(await this.repository.withdraw(evidenceId, expectedRevision, this.mutation(context, "withdraw_evidence", key, fingerprint))); }
  async listEvidence(context: RequestContext, agreementId: string, versionId: string) { await this.scope(context, agreementId, versionId); return this.repository.listEvidence(agreementId, versionId); }
  async getEvidence(context: RequestContext, agreementId: string, evidenceId: string) { const item = await this.repository.getEvidence(agreementId, evidenceId); if (!item) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); await this.scope(context, agreementId, item.versionId); return { ...item, revisions: await this.repository.listEvidenceRevisions(evidenceId) }; }
  async workflowContext(context: RequestContext, agreementId: string, versionId: string) { const scope = await this.scope(context, agreementId, versionId); const items = await this.repository.listEvidence(agreementId, versionId); const requirementStates = scope.document.evidencePolicy.evidenceRequirements.map((requirement) => ({ evidenceRequirementId: requirement.evidenceRequirementId, ...requirementState(items.filter((item) => item.evidenceRequirementId === requirement.evidenceRequirementId && item.lifecycle === "active").map((item) => item.currentRevision), requirement.minimumDistinctSources, requirement.independentSourcesRequired) })); return { agreementId, versionId, acceptedAgreementVersion: scope.document.agreementVersion, versionState: scope.document.versionState, partyId: scope.membership.partyId, role: scope.membership.role, canSubmitEvidence: scope.document.evidencePolicy.evidenceRequirements.some((requirement) => requirement.submitterPartyIds.includes(scope.membership.partyId)), canAssignReview: scope.membership.role === "reviewer", canRecordReviewerDecision: scope.membership.role === "reviewer", requirementStates }; }

  async requestAssessment(context: RequestContext, agreementId: string, versionId: string, adapter: AssessmentAdapter, key: string, fingerprint: string) {
    const scope = await this.scope(context, agreementId, versionId); const items = (await this.repository.listEvidence(agreementId, versionId)).filter((i) => i.lifecycle === "active"); const revisions = items.map((i) => i.currentRevision); const states = new Map(scope.document.evidencePolicy.evidenceRequirements.map((r) => [r.evidenceRequirementId, requirementState(revisions.filter((e) => items.find((i) => i.evidenceId === e.evidenceId)?.evidenceRequirementId === r.evidenceRequirementId), r.minimumDistinctSources, r.independentSourcesRequired).state]));
    const canonical = evidenceSetDigest(agreementId, versionId, revisions.map((r) => r.evidenceRevisionId)); const createdAt = this.now().toISOString(); const set: EvidenceSet = { evidenceSetId: this.ids("evidence-set"), agreementId, versionId, canonicalizationVersion: "evidence-set-v1", digest: canonical.digest, evidenceRevisionIds: canonical.ordered, createdAt, createdByAccountId: scope.accountId };
    const draft = await adapter.evaluate({ document: scope.document, evidence: revisions, requirementStates: states }); const allowedCriteria = new Set(scope.document.verificationPolicy.criterionIds); const allowedRevisions = new Set(canonical.ordered); if (draft.findings.length > 100 || draft.findings.some((finding) => !allowedCriteria.has(finding.criterionId) || finding.explanation.length > 2_000 || [...finding.supportingEvidenceRevisionIds, ...finding.conflictingEvidenceRevisionIds].some((id) => !allowedRevisions.has(id)))) throw new EvidenceError("EVIDENCE_INVALID", "The assessment output is invalid."); const assessment: Assessment = { assessmentId: this.ids("assessment"), agreementId, versionId, evidenceSetId: set.evidenceSetId, adapterKind: adapter.kind, adapterVersion: adapter.version, policyVersion: scope.document.verificationPolicy.policyVersion, status: "completed", criterionFindings: draft.findings, confidence: draft.confidence, limitations: draft.limitations, recommendedNextAction: draft.recommendedNextAction, occurredAt: createdAt, revision: 1 };
    return this.outcome(await this.repository.saveAssessment(set, assessment, this.mutation(context, "request_assessment", key, fingerprint)));
  }
  async listAssessments(context: RequestContext, agreementId: string, versionId: string) { await this.scope(context, agreementId, versionId); return this.repository.listAssessments(agreementId); }
  async getAssessment(context: RequestContext, agreementId: string, id: string) { const value = await this.repository.getAssessment(agreementId, id); if (!value) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); await this.scope(context, agreementId, value.versionId); return value; }

  async requestHumanReview(context: RequestContext, agreementId: string, versionId: string, input: { assessmentId?: string; evidenceSetId?: string; reasonCodes: ReviewReason[]; affectedCriterionIds: string[] }, key: string, fingerprint: string) { const scope = await this.scope(context, agreementId, versionId); const createdAt = this.now().toISOString(); const request: HumanReviewRequest = { reviewRequestId: this.ids("review"), agreementId, versionId, ...input, reasonCodes: [...new Set(input.reasonCodes)].sort(), affectedCriterionIds: [...new Set(input.affectedCriterionIds)].sort(), requestedByAccountId: scope.accountId, route: scope.document.verificationPolicy.reviewRoute, state: "open", createdAt, updatedAt: createdAt, revision: 1 }; return this.outcome(await this.repository.saveReview(request, this.mutation(context, "request_human_review", key, fingerprint))); }
  async assignReview(context: RequestContext, agreementId: string, id: string, expectedRevision: number) { const request = await this.repository.getReview(agreementId, id); if (!request) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); const scope = await this.scope(context, agreementId, request.versionId); if (scope.membership.role !== "reviewer") throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); const result = await this.repository.assignReview(id, scope.accountId, expectedRevision); if (!result) throw new EvidenceError("REVIEW_CONFLICT", "The review request changed before this request completed.", 409); return result; }
  async recordReviewerDecision(context: RequestContext, agreementId: string, id: string, expectedRevision: number, input: Omit<ReviewerDecision, "reviewerDecisionId" | "reviewRequestId" | "agreementId" | "versionId" | "reviewerAccountId" | "reviewerPartyId" | "authorityBasis" | "createdAt">, key: string, fingerprint: string) { const request = await this.repository.getReview(agreementId, id); if (!request) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); const scope = await this.scope(context, agreementId, request.versionId); if (scope.membership.role !== "reviewer" || request.assignedAccountId !== scope.accountId || request.route !== scope.document.verificationPolicy.reviewRoute) throw new EvidenceError("RESOURCE_NOT_FOUND", "The resource was not found.", 404); const items = await this.repository.listEvidence(agreementId, request.versionId); if (items.some((item) => input.evidenceRevisionIds.includes(item.currentRevisionId) && (item.currentRevision.submittedByAccountId === scope.accountId || item.currentRevision.submittedByPartyId === scope.membership.partyId))) throw new EvidenceError("EVIDENCE_NOT_ALLOWED", "A reviewer cannot decide a challenge to their own evidence.", 403); const decision: ReviewerDecision = { ...input, reviewerDecisionId: this.ids("decision"), reviewRequestId: id, agreementId, versionId: request.versionId, reviewerAccountId: scope.accountId, reviewerPartyId: scope.membership.partyId, authorityBasis: "active_assigned_reviewer_membership", createdAt: this.now().toISOString() }; return this.outcome(await this.repository.decideReview(id, expectedRevision, decision, this.mutation(context, "record_reviewer_decision", key, fingerprint))); }
  async listReviews(context: RequestContext, agreementId: string, versionId: string) { await this.scope(context, agreementId, versionId); return this.repository.listReviews(agreementId); }
  async listReviewerDecisions(context: RequestContext, agreementId: string, versionId: string) { await this.scope(context, agreementId, versionId); return this.repository.listReviewerDecisions(agreementId); }
}
