/* eslint-disable @typescript-eslint/no-explicit-any -- Prisma aggregate shapes remain generated and transaction-specific. */
import { createHash, randomUUID } from "node:crypto";
import type { Prisma, PrismaClient } from "@prisma/client";
import type { AgreementLanguageDocument } from "../../lib/agreement-language/types.ts";
import type { RequestContext } from "../agreements/application/contracts.ts";
import { balancedEntries, canTransition, consequenceRef, evaluateResolutionReadiness, explicitRequirement, TERMINAL_STATES, validateEffect, type FinancialSafetyState, type ResolutionState, type SimulatedEffect } from "./domain.ts";

export class ResolutionError extends Error { constructor(public code: string, message: string, public status = 422, public revision?: number) { super(message); this.name = code; } }
type Mutation = { key: string; fingerprint: string; expectedRevision?: number };
const json = <T>(value: T) => value as Prisma.InputJsonValue;
const view = (proposal: any) => ({ ...proposal, simulation: true, effectiveState: proposal.state, simulatedEffect: proposal.simulatedEffect as SimulatedEffect });

export class ResolutionService {
  constructor(private prisma: PrismaClient, private clock = () => new Date()) {}
  private actor(context: RequestContext) { if (context.principal.kind !== "account" || context.principal.accountState !== "active") throw new ResolutionError("AUTHENTICATION_REQUIRED", "An active account session is required.", 401); return context.principal; }
  private async membership(tx: Prisma.TransactionClient | PrismaClient, agreementId: string, accountId: string) { const member = await tx.agreementMembership.findFirst({ where: { agreementId, accountId, state: "active" } }); if (!member) throw new ResolutionError("RESOURCE_NOT_FOUND", "The resolution is unavailable.", 404); return member; }
  private async idem(tx: Prisma.TransactionClient, actorId: string, operation: string, agreementId: string, mutation: Mutation) {
    const digest = createHash("sha256").update(mutation.key).digest("hex");
    const prior = await tx.idempotencyRecord.findUnique({ where: { actorId_operation_normalizedScope_keyDigest: { actorId, operation, normalizedScope: agreementId, keyDigest: digest } } });
    if (prior) { if (prior.requestFingerprint !== mutation.fingerprint) throw new ResolutionError("IDEMPOTENCY_KEY_REUSED", "That idempotency key was used for different information.", 409); return prior; }
    return { digest };
  }
  private async remember(tx: Prisma.TransactionClient, actorId: string, operation: string, agreementId: string, mutation: Mutation, resourceId: string, versionId: string, digest: string) { const now = this.clock(); await tx.idempotencyRecord.create({ data: { id: `idem-${randomUUID()}`, actorId, operation, agreementScopeId: agreementId, normalizedScope: agreementId, keyDigest: digest, requestFingerprint: mutation.fingerprint, agreementId, resultVersionId: versionId, resultResourceType: "resolution", resultResourceId: resourceId, createdAt: now, expiresAt: new Date(now.getTime() + 86_400_000) } }); }
  private async proposal(tx: Prisma.TransactionClient | PrismaClient, agreementId: string, proposalId: string): Promise<any> { const proposal = await tx.proposedResolution.findFirst({ where: { id: proposalId, agreementId }, include: { disputes: true, grants: true, execution: { include: { intent: true, events: true, ledgerTransaction: { include: { entries: true } } } } } }); if (!proposal) throw new ResolutionError("RESOURCE_NOT_FOUND", "The resolution is unavailable.", 404); return proposal; }
  async list(context: RequestContext, agreementId: string) { const actor = this.actor(context); await this.membership(this.prisma, agreementId, actor.accountId); return (await this.prisma.proposedResolution.findMany({ where: { agreementId }, include: { disputes: true, grants: true, execution: { include: { intent: true, events: { orderBy: [{ occurredAt: "asc" }, { id: "asc" }] }, ledgerTransaction: { include: { entries: { orderBy: { id: "asc" } } } } } }, audits: { orderBy: [{ occurredAt: "asc" }, { id: "asc" }] }, domainEvents: { orderBy: [{ occurredAt: "asc" }, { id: "asc" }] } }, orderBy: [{ createdAt: "desc" }, { id: "desc" }] })).map(view); }
  async get(context: RequestContext, agreementId: string, proposalId: string) { const actor = this.actor(context); await this.membership(this.prisma, agreementId, actor.accountId); return view(await this.proposal(this.prisma, agreementId, proposalId)); }
  async propose(context: RequestContext, agreementId: string, input: { versionId: string; resolutionOutcomeId: string; evidenceSetId: string; assessmentId: string; reviewerDecisionId?: string; proposalSource: "deterministic_assessment" | "human_reviewer"; simulatedEffect: SimulatedEffect; expiresAt?: string }, mutation: Mutation) {
    const actor = this.actor(context); const now = this.clock();
    return this.prisma.$transaction(async (tx) => { const member = await this.membership(tx, agreementId, actor.accountId); const replay = await this.idem(tx, actor.accountId, "propose_resolution", agreementId, mutation); if (!("digest" in replay)) return { replayed: true, resource: view(await this.proposal(tx, agreementId, replay.resultResourceId!)) };
      const version = await tx.agreementVersion.findUnique({ where: { agreementId_id: { agreementId, id: input.versionId } }, include: { acceptances: true } }); if (!version) throw new ResolutionError("RESOURCE_NOT_FOUND", "The accepted version is unavailable.", 404); const document = version.document as unknown as AgreementLanguageDocument;
      const recordAuthority = explicitRequirement(document, "record_resolution"); if (!recordAuthority) throw new ResolutionError("RECORD_RESOLUTION_AUTHORITY_AMENDMENT_REQUIRED", "The accepted agreement does not contain one unambiguous record-resolution authority. Materially amend it and renew every required acceptance before proposing a resolution.");
      if (version.versionState !== "accepted" || document.versionState !== "accepted" || document.parties.filter((p) => p.acceptanceRequired).some((p) => !version.acceptances.some((a) => a.partyId === p.partyId))) throw new ResolutionError("VERSION_NOT_ACCEPTED", "Every required party must accept this exact agreement version.");
      if (!recordAuthority.eligiblePartyIds.includes(member.partyId)) throw new ResolutionError("RESOURCE_NOT_FOUND", "The resolution is unavailable.", 404);
      if (!Number.isSafeInteger(document.resolutionPolicy.reviewWindowSeconds) || document.resolutionPolicy.reviewWindowSeconds < 0 || document.resolutionPolicy.reviewWindowSeconds > 31_536_000) throw new ResolutionError("INVALID_REVIEW_WINDOW", "The accepted review window is outside the supported range.");
      const outcome = document.resolutionPolicy.outcomes.find((item) => item.outcomeId === input.resolutionOutcomeId); if (!outcome) throw new ResolutionError("OUTCOME_NOT_FOUND", "The outcome is not part of the accepted version.");
      const [set, assessment, decision] = await Promise.all([tx.evidenceSet.findFirst({ where: { id: input.evidenceSetId, agreementId, versionId: input.versionId } }), tx.assessment.findFirst({ where: { id: input.assessmentId, agreementId, versionId: input.versionId, evidenceSetId: input.evidenceSetId }, include: { findings: true } }), input.reviewerDecisionId ? tx.reviewerDecision.findFirst({ where: { id: input.reviewerDecisionId, agreementId, versionId: input.versionId, evidenceSetId: input.evidenceSetId } }) : null]); if (!set || !assessment || (input.reviewerDecisionId && !decision)) throw new ResolutionError("SNAPSHOT_MISMATCH", "Evidence, assessment, and review references must match the exact accepted version.");
      const effectErrors = validateEffect(document, input.simulatedEffect); if (effectErrors.length) throw new ResolutionError(effectErrors[0], "The simulated consequence does not satisfy the accepted economic-side policy.");
      const ref = consequenceRef(input.versionId, input.resolutionOutcomeId, input.simulatedEffect); const existing = await tx.proposedResolution.findFirst({ where: { agreementId, versionId: input.versionId, resolutionOutcomeId: input.resolutionOutcomeId, state: { notIn: TERMINAL_STATES } } }); if (existing) throw new ResolutionError("ACTIVE_PROPOSAL_EXISTS", "A non-terminal proposal already exists for this outcome.", 409, existing.revision);
      const expiresAt = input.expiresAt ? new Date(input.expiresAt) : null; if (expiresAt && !document.terms.deadlines.some((deadline) => deadline.instant === input.expiresAt && deadline.onReached === "expire")) throw new ResolutionError("PROPOSAL_EXPIRY_NOT_AUTHORIZED", "Expiry may only come from an accepted agreement deadline or outcome rule.");
      const id = `resolution-${randomUUID()}`; const ends = new Date(now.getTime() + document.resolutionPolicy.reviewWindowSeconds * 1000); const proposal = await tx.proposedResolution.create({ data: { id, agreementId, versionId: input.versionId, agreementDocumentDigest: version.documentDigest!, resolutionOutcomeId: input.resolutionOutcomeId, consequenceRef: ref, evidenceSetId: input.evidenceSetId, assessmentId: input.assessmentId, reviewerDecisionId: input.reviewerDecisionId, proposalSource: input.proposalSource, simulatedEffect: json(input.simulatedEffect), policySnapshot: json({ authorizationPolicy: document.authorizationPolicy, resolutionPolicy: document.resolutionPolicy, economicSides: document.economicSides, protectionPolicy: document.protectionPolicy }), reviewWindowSeconds: document.resolutionPolicy.reviewWindowSeconds, proposedAt: now, reviewWindowEndsAt: ends, expiresAt, state: "review_window_open", revision: 1, createdByAccountId: actor.accountId, createdAt: now, updatedAt: now } }); await tx.financialSafetyStatus.upsert({ where: { agreementId_versionId: { agreementId, versionId: input.versionId } }, create: { agreementId, versionId: input.versionId, state: document.financialSafetyPolicy.initialState, updatedAt: now }, update: {} }); await this.audit(tx, proposal, actor.accountId, "ResolutionProposed", null, "review_window_open", context.correlationId); await this.remember(tx, actor.accountId, "propose_resolution", agreementId, mutation, id, input.versionId, replay.digest); return { replayed: false, resource: view(proposal) }; }, { isolationLevel: "Serializable" });
  }
  private async readinessData(tx: Prisma.TransactionClient | PrismaClient, proposal: any, at: Date) { const version = await tx.agreementVersion.findUnique({ where: { agreementId_id: { agreementId: proposal.agreementId, id: proposal.versionId } }, include: { acceptances: true } }); if (!version) throw new ResolutionError("SNAPSHOT_MISMATCH", "The accepted version snapshot is unavailable."); const assessment = await tx.assessment.findUnique({ where: { id: proposal.assessmentId }, include: { findings: true } }); const safety = await tx.financialSafetyStatus.findUnique({ where: { agreementId_versionId: { agreementId: proposal.agreementId, versionId: proposal.versionId } } }); if (!assessment || !safety) throw new ResolutionError("SNAPSHOT_MISMATCH", "The proposal snapshot is incomplete."); const document = version.document as unknown as AgreementLanguageDocument; return evaluateResolutionReadiness({ state: proposal.state, versionId: proposal.versionId, document, documentDigest: version.documentDigest ?? "", expectedDocumentDigest: proposal.agreementDocumentDigest, acceptedPartyIds: version.acceptances.map((x) => x.partyId), outcomeId: proposal.resolutionOutcomeId, consequenceRef: proposal.consequenceRef, effect: proposal.simulatedEffect as SimulatedEffect, assessment: { status: assessment.status, results: assessment.findings.map((x) => x.result), recommendedNextAction: assessment.recommendedNextAction }, reviewerDecisionPresent: Boolean(proposal.reviewerDecisionId), reviewWindowEndsAt: proposal.reviewWindowEndsAt.toISOString(), expiresAt: proposal.expiresAt?.toISOString(), activeDispute: proposal.disputes.some((x: any) => ["open", "under_review", "appealed"].includes(x.status)), financialSafetyState: safety.state, grants: proposal.grants.map((x: any) => ({ ...x, grantedAt: x.grantedAt.toISOString(), expiresAt: x.expiresAt?.toISOString(), revokedAt: x.revokedAt?.toISOString() })), priorExecution: Boolean(proposal.execution), createdByPartyId: (await this.membership(tx, proposal.agreementId, proposal.createdByAccountId)).partyId }, at); }
  async evaluate(context: RequestContext, agreementId: string, proposalId: string) { const actor = this.actor(context); await this.membership(this.prisma, agreementId, actor.accountId); const proposal = await this.proposal(this.prisma, agreementId, proposalId); return this.readinessData(this.prisma, proposal, this.clock()); }
  async dispute(context: RequestContext, agreementId: string, proposalId: string, input: { reasonCode: string; explanation: string }, mutation: Mutation) {
    return this.change(context, agreementId, proposalId, "submit_dispute", mutation, async (tx, proposal, member, actor, now) => {
      if (TERMINAL_STATES.includes(proposal.state)) throw new ResolutionError("PROPOSAL_TERMINAL", "A terminal resolution cannot be disputed.", 409, proposal.revision);
      if (!/^[a-z_]{3,64}$/.test(input.reasonCode) || !input.explanation.trim() || input.explanation.length > 2000) throw new ResolutionError("INVALID_REQUEST", "Provide a bounded dispute reason and explanation.", 400);
      const version = await tx.agreementVersion.findUnique({ where: { agreementId_id: { agreementId, id: proposal.versionId } } });
      const document = version!.document as unknown as AgreementLanguageDocument;
      const id = `dispute-${randomUUID()}`; const reviewRequestId = `review-${randomUUID()}`;
      await tx.humanReviewRequest.create({ data: { id: reviewRequestId, agreementId, versionId: proposal.versionId, assessmentId: proposal.assessmentId, evidenceSetId: proposal.evidenceSetId, reasonCodes: ["participant_challenge"], affectedCriterionIds: document.verificationPolicy.criterionIds, requestedByAccountId: actor.accountId, route: document.verificationPolicy.reviewRoute, state: "open", createdAt: now, updatedAt: now } });
      await tx.resolutionDispute.create({ data: { id, proposalId, agreementId, versionId: proposal.versionId, openedByPartyId: member.partyId, openedByAccountId: actor.accountId, status: "open", reasonCode: input.reasonCode, explanation: input.explanation, reviewRequestId, rootDisputeId: id, appealOrdinal: 0, openedAt: now } });
      return { state: "disputed" as ResolutionState, event: "DisputeSubmitted", resourceId: id };
    });
  }
  async resolveDispute(context: RequestContext, agreementId: string, proposalId: string, disputeId: string, input: { reviewerDecisionId: string }, mutation: Mutation) {
    return this.change(context, agreementId, proposalId, "resolve_dispute", mutation, async (tx, proposal, member, _actor, now) => {
      if (member.role !== "reviewer") throw new ResolutionError("RESOURCE_NOT_FOUND", "The dispute is unavailable.", 404);
      const dispute = await tx.resolutionDispute.findFirst({ where: { id: disputeId, proposalId, agreementId, versionId: proposal.versionId, status: { in: ["open", "under_review", "appealed"] } } });
      const decision = dispute?.reviewRequestId ? await tx.reviewerDecision.findFirst({ where: { id: input.reviewerDecisionId, reviewRequestId: dispute.reviewRequestId, agreementId, versionId: proposal.versionId, reviewerAccountId: member.accountId! } }) : null;
      if (!dispute || !decision) throw new ResolutionError("RESOURCE_NOT_FOUND", "A matching completed reviewer decision is required.", 404);
      await tx.resolutionDispute.update({ where: { id: dispute.id }, data: { status: "resolved", reviewerDecisionId: decision.id, resolvedAt: now, revision: { increment: 1 } } });
      return { state: "held", event: "DisputeResolved", resourceId: dispute.id };
    });
  }
  async grant(context: RequestContext, agreementId: string, proposalId: string, mutation: Mutation) { return this.change(context, agreementId, proposalId, "grant_authorization", mutation, async (tx, proposal, member, actor, now) => { const version = await tx.agreementVersion.findUnique({ where: { agreementId_id: { agreementId, id: proposal.versionId } } }); const requirement = explicitRequirement(version!.document as unknown as AgreementLanguageDocument, "create_settlement_instruction"); if (!requirement?.eligiblePartyIds.includes(member.partyId)) throw new ResolutionError("RESOURCE_NOT_FOUND", "The resolution is unavailable.", 404); const grant = await tx.resolutionAuthorizationGrant.upsert({ where: { proposalId_action_partyId_consequenceRef: { proposalId, action: "create_settlement_instruction", partyId: member.partyId, consequenceRef: proposal.consequenceRef } }, create: { id: `authorization-${randomUUID()}`, proposalId, agreementId, versionId: proposal.versionId, partyId: member.partyId, accountId: actor.accountId, action: "create_settlement_instruction", consequenceRef: proposal.consequenceRef, sessionAssurance: actor.assurance, grantedAt: now }, update: { revokedAt: null, grantedAt: now, revision: { increment: 1 } } }); return { state: proposal.state as ResolutionState, event: "AuthorizationGranted", resourceId: grant.id }; }); }
  async revoke(context: RequestContext, agreementId: string, proposalId: string, authorizationId: string, mutation: Mutation) { return this.change(context, agreementId, proposalId, "revoke_authorization", mutation, async (tx, proposal, member, actor, now) => { const grant = await tx.resolutionAuthorizationGrant.findFirst({ where: { id: authorizationId, proposalId, accountId: actor.accountId, partyId: member.partyId } }); if (!grant) throw new ResolutionError("RESOURCE_NOT_FOUND", "The authorization is unavailable.", 404); await tx.resolutionAuthorizationGrant.update({ where: { id: grant.id }, data: { revokedAt: now, revision: { increment: 1 } } }); return { state: "held" as ResolutionState, event: "AuthorizationRevoked", resourceId: grant.id }; }); }
  async safety(context: RequestContext, agreementId: string, proposalId: string, input: { state: FinancialSafetyState; reasonCode: string }, mutation: Mutation) { return this.change(context, agreementId, proposalId, "transition_financial_safety", mutation, async (tx, proposal, member, actor, now) => { if (!["owner", "reviewer"].includes(member.role)) throw new ResolutionError("RESOURCE_NOT_FOUND", "The resolution is unavailable.", 404); const status = await tx.financialSafetyStatus.findUnique({ where: { agreementId_versionId: { agreementId, versionId: proposal.versionId } } }); if (!status) throw new ResolutionError("SNAPSHOT_MISMATCH", "Financial Safety must be initialized explicitly."); await tx.financialSafetyStatus.update({ where: { agreementId_versionId: { agreementId, versionId: proposal.versionId } }, data: { state: input.state, revision: { increment: 1 }, updatedAt: now } }); await tx.financialSafetyTransition.create({ data: { id: `safety-${randomUUID()}`, agreementId, versionId: proposal.versionId, proposalId, fromState: status.state, toState: input.state, reasonCode: input.reasonCode, actorAccountId: actor.accountId, authorityBasis: `active_${member.role}_development_policy`, correlationId: context.correlationId, occurredAt: now } }); return { state: input.state === "clear" ? proposal.state as ResolutionState : "held", event: input.state === "clear" ? "FinancialSafetyCleared" : "ResolutionHeld", resourceId: proposalId }; }); }
  async cancel(context: RequestContext, agreementId: string, proposalId: string, mutation: Mutation) { return this.change(context, agreementId, proposalId, "cancel_resolution", mutation, async (_tx, proposal, member) => { if (TERMINAL_STATES.includes(proposal.state)) throw new ResolutionError("PROPOSAL_TERMINAL", "A terminal resolution cannot be cancelled.", 409, proposal.revision); const document = (await _tx.agreementVersion.findUnique({ where: { agreementId_id: { agreementId, id: proposal.versionId } } }))!.document as unknown as AgreementLanguageDocument; if (!document.resolutionPolicy.cancellation.eligibleInitiatorPartyIds.includes(member.partyId)) throw new ResolutionError("RESOURCE_NOT_FOUND", "The resolution is unavailable.", 404); return { state: "cancelled", event: "ResolutionCancelled", resourceId: proposalId }; }); }
  async execute(context: RequestContext, agreementId: string, proposalId: string, mutation: Mutation) { const actor = this.actor(context); const now = this.clock(); return this.prisma.$transaction(async (tx) => { await this.membership(tx, agreementId, actor.accountId); const replay = await this.idem(tx, actor.accountId, "execute_simulated", agreementId, mutation); if (!("digest" in replay)) { const proposal = await this.proposal(tx, agreementId, proposalId); return { replayed: true, resource: view(proposal) }; } const proposal = await this.proposal(tx, agreementId, proposalId); if (mutation.expectedRevision !== proposal.revision) throw new ResolutionError("RESOLUTION_CONFLICT", "The resolution changed; review its current state.", 409, proposal.revision); const readiness = await this.readinessData(tx, proposal, now); if (!readiness.ready) throw new ResolutionError(readiness.blockers[0], "The simulated consequence is not execution-ready.", 409, proposal.revision); const executionId = `execution-${randomUUID()}`; const intentId = `intent-${randomUUID()}`; const entries = balancedEntries(proposal.simulatedEffect as SimulatedEffect); await tx.simulatedSettlementExecution.create({ data: { id: executionId, proposalId, consequenceExecutionKey: `${proposal.versionId}:${proposal.consequenceRef}`, executionMode: "simulated", executedByAccountId: actor.accountId, executedAt: now, correlationId: context.correlationId, intent: { create: { id: intentId, proposalId, consequenceRef: proposal.consequenceRef, executionMode: "simulated", effect: proposal.simulatedEffect, createdAt: now } }, events: { create: [{ id: `event-${randomUUID()}`, eventType: "intent_created", executionMode: "simulated", actorId: actor.accountId, correlationId: context.correlationId, occurredAt: now }, { id: `event-${randomUUID()}`, eventType: "simulated_executed", executionMode: "simulated", actorId: actor.accountId, correlationId: context.correlationId, causationId: intentId, occurredAt: now }] }, ...(entries.length ? { ledgerTransaction: { create: { id: `ledger-${randomUUID()}`, currency: entries[0].currency, createdAt: now, entries: { create: entries.map((entry) => ({ id: `ledger-entry-${randomUUID()}`, ...entry })) } } } } : {}) } }); const updated = await tx.proposedResolution.update({ where: { id: proposalId }, data: { state: "simulated_executed", revision: { increment: 1 }, updatedAt: now } }); await this.audit(tx, updated, actor.accountId, "SimulatedSettlementExecuted", proposal.state, "simulated_executed", context.correlationId); await this.remember(tx, actor.accountId, "execute_simulated", agreementId, mutation, proposalId, proposal.versionId, replay.digest); return { replayed: false, resource: view(await this.proposal(tx, agreementId, proposalId)) }; }, { isolationLevel: "Serializable" }); }
  private async change(context: RequestContext, agreementId: string, proposalId: string, operation: string, mutation: Mutation, action: (tx: Prisma.TransactionClient, proposal: any, member: any, actor: any, now: Date) => Promise<{ state: ResolutionState; event: string; resourceId: string }>) { const actor = this.actor(context); const now = this.clock(); return this.prisma.$transaction(async (tx) => { const member = await this.membership(tx, agreementId, actor.accountId); const replay = await this.idem(tx, actor.accountId, operation, agreementId, mutation); if (!("digest" in replay)) return { replayed: true, resource: view(await this.proposal(tx, agreementId, proposalId)) }; const proposal = await this.proposal(tx, agreementId, proposalId); if (mutation.expectedRevision !== proposal.revision) throw new ResolutionError("RESOLUTION_CONFLICT", "The resolution changed; review its current state.", 409, proposal.revision); if (TERMINAL_STATES.includes(proposal.state)) throw new ResolutionError("PROPOSAL_TERMINAL", "A terminal resolution cannot be changed.", 409, proposal.revision); const result = await action(tx, proposal, member, actor, now); if (result.state !== proposal.state && !canTransition(proposal.state, result.state)) throw new ResolutionError("INVALID_RESOLUTION_TRANSITION", "The requested resolution transition is not allowed.", 409, proposal.revision); const updated = result.state === proposal.state ? proposal : await tx.proposedResolution.update({ where: { id: proposalId }, data: { state: result.state, revision: { increment: 1 }, updatedAt: now } }); await this.audit(tx, updated, actor.accountId, result.event, proposal.state, result.state, context.correlationId); await this.remember(tx, actor.accountId, operation, agreementId, mutation, result.resourceId, proposal.versionId, replay.digest); return { replayed: false, resource: view(await this.proposal(tx, agreementId, proposalId)) }; }, { isolationLevel: "Serializable" }); }
  private async audit(tx: Prisma.TransactionClient, proposal: any, actorId: string, event: string, fromState: ResolutionState | null, toState: ResolutionState, correlationId: string) { const now = this.clock(); await tx.resolutionAuditEvent.create({ data: { id: `resolution-audit-${randomUUID()}`, proposalId: proposal.id, action: event, actorId, fromState, toState, reasonCodes: [], correlationId, occurredAt: now } }); await tx.resolutionDomainEvent.create({ data: { id: `resolution-domain-${randomUUID()}`, proposalId: proposal.id, eventType: event, payload: { simulation: true, proposalId: proposal.id, versionId: proposal.versionId }, correlationId, occurredAt: now } }); }
}
